name: Validate/build docs and push

on:
  push:
    paths:
      - 'trento_suse_docs/DC-*'
      - 'trento_suse_docs/xml/**'
      - 'trento_suse_docs/adoc/**'
      - 'trento_suse_docs/images/src/**'
      - 'trento_suse_docs/**/DC-*'
      - 'trento_suse_docs/**/xml/**'
      - 'trento_suse_docs/**/adoc/**'
      - 'trento_suse_docs/**/images/src/**'
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - 'trento_suse_docs/DC-*'
      - 'trento_suse_docs/xml/**'
      - 'trento_suse_docs/adoc/**'
      - 'trento_suse_docs/images/src/**'
      - 'trento_suse_docs/**/DC-*'
      - 'trento_suse_docs/**/xml/**'
      - 'trento_suse_docs/**/adoc/**'
      - 'trento_suse_docs/**/images/src/**'

jobs:
  select-dc-files:
    runs-on: ubuntu-latest
    outputs:
      validate-list: ${{ steps.select-dc-validate.outputs.dc-list }}
      build-list: ${{ steps.select-dc-build.outputs.dc-list }}
      allow-build: ${{ steps.select-dc-build.outputs.allow-build }}
      relevant-branches: ${{ steps.select-dc-build.outputs.relevant-branches }}
    steps:
      - uses: actions/checkout@v4

      - name: Checking basic soundness of DC files
        uses: openSUSE/doc-ci@gha-select-dcs
        with:
          mode: soundness

      - name: Selecting DC files to validate
        id: select-dc-validate
        uses: openSUSE/doc-ci@gha-select-dcs
        with:
          mode: list-validate

      - name: Selecting DC files to build
        id: select-dc-build
        uses: openSUSE/doc-ci@gha-select-dcs
        with:
          mode: list-build
          original-org: trento-project

  validate:
    runs-on: ubuntu-latest
    needs: select-dc-files
    strategy:
      # don't cancel all validation runners when one of them fails, we want full results
      fail-fast: false
      matrix:
        dc-files: ${{ fromJson(needs.select-dc-files.outputs.validate-list) }}
    steps:
      - uses: actions/checkout@v4
      - name: Validating DC file(s) ${{ matrix.dc-files }}
        uses: openSUSE/doc-ci@gha-validate
        with:
          dc-files: ${{ matrix.dc-files }}
  open-pr-to-doc-unversioned:
    if: github.ref == 'refs/heads/restructure_docs_directory'
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - name: Checkout source repo (docs repo)
        uses: actions/checkout@v4
    
      - name: Clone doc-unversioned
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      
          git clone https://x-access-token:${{ secrets.DOC_UNVERSIONED_PAT }}@github.com/EMaksy/doc-unversioned.git

          cd doc-unversioned
          git fetch origin
          git checkout main          
          git checkout -b sync-trento-docs

          cp -r ../trento_suse_docs/* trento/
          git add trento/*
          git commit -m "Sync user-docs content to doc-unversioned trento/ after CI success"
          git push origin sync-trento-docs
      - name: Debug Repo
        run: echo "Running in $GITHUB_REPOSITORY"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.DOC_UNVERSIONED_PAT }}
          title: "Sync docs after CI success"
          body: "Triggered by workflow run sync-trento-docs"
          base: main
          branch: sync-trento-docs
