site:
  title: Trento Documentation
  url: https://trento-project.github.io
  start_page: docs::index.adoc

content:
  sources:
    - url: .
      branches:
        - HEAD
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true

output:
  dir: ./antora_public

antora:
  extensions:
  - '@antora/collector-extension'
  - require: '@antora/lunr-extension'
    index_latest_only: true


        