= Trento Documentation

The Trento docs live at the link:https://www.trento-project.io/docs[documentation hub], powered by link:https://antora.org/[Antora].
The hub publishes two tracks:

* **Pre-release (main)** – includes the newest changes and upcoming features.
* **Stable (latest)** – the most recent released version.

Content is sourced from multiple upstream Trento repositories and from the dedicated content repo:
link:https://github.com/trento-project/docs-content[trento-project/docs-content].

== Trento docs site

The `trento-docs-site` directory contains the Antora playbook, build scripts, and configuration used to assemble the
link:https://www.trento-project.io/docs/[unified documentation site].  
For details, see xref:trento-docs-site/README.adoc[Documentation hub (site) README].

== Trento docs site UI

The `trento-docs-site-ui` directory customizes the look & feel of the site (theme, navigation, search UI, etc.) and produces
the Antora UI bundle.  
Learn more in xref:trento-docs-site-ui/README.adoc[UI customization README].