= Trento docs
ifndef::site-gen-antora[:relfileprefix: /content/]

This repository contains the Trento project documentation that does not interest a specific service, such as ADR, coding standards and best practices, CI workflows, and templates. The link:https://github.com/trento-project/docs/tree/main/content[*content* directory] is the home of these sources.
 
* xref:architecture/trento-architecture.adoc[Architecture]
* xref:architecture/adr/README.adoc[Architecture Decision Records (ADR)]
* xref:coding-standards/README.adoc[Coding standards]
* link:https://github.com/trento-project/docs/tree/main/content/rfc[Request for Comments (RFC)]
* link:https://github.com/trento-project/docs/tree/main/content/internal_notes[Internal Notes]
* link:https://github.com/trento-project/docs/tree/main/content/templates[Templates]
* link:https://github.com/trento-project/docs/tree/main/content/guides[Guides]

== Trento docs site

The `trento-docs-site` directory builds the link:https://www.trento-project.io/docs/[Trento project’s unified documentation site] using https://antora.org/[Antora]. Learn more about xref:trento-docs-site/README.adoc[the documentation hub here].


== Trento docs site ui

The `trento-docs-site-ui` directory is used to customize and design the layout of the link:https://www.trento-project.io/docs/[Trento docs site]. Learn more about the xref:trento-docs-site-ui/README.adoc[ui customization here].