include::product-attributes.adoc[]

[[sec-trento-report-problem]]
== Reporting an Issue
:revdate: 2025-10-27


{suse} customers with registered {sles4sap}{nbsp}15 (SP4 or higher)
distributions can report {trento} issues either directly in the {scc}
or through the corresponding vendor, depending on their licensing model.
Problems must be reported under {sles4sap}{nbsp}15 and component
trento.

When opening a support case for {trento}, provide the relevant
deployment option for {trserver}: {k8s}, or systemd rpm installation.

In case of a {k8s} deployment, provide the output of the {trento}
support script as explained in section
<<sec-trento-problemanalysis>>.

In case of a systemd deployment, provide the output of the {trento} support plugin, as explained in section <<sec-trento-problemanalysis>>.

For issues with a particular {tragent}, or a component discovered by a
particular {tragent}, also provide the following:

* status of the {tragent}
* journal of the {tragent}
* output of the command `+supportconfig+` in the {tragent} host. See
https://documentation.suse.com/sles/html/SLES-all/cha-adm-support.html#sec-admsupport-cli
for information on how to run this command from command line.
