include::product-attributes.adoc[]

[[sec-trento-updating-trentoserver]]
=== Updating {trserver}
:revdate: 2025-06-10


The procedure to update {trserver} depends on the chosen deployment
option: {k8s} or systemd.

Consider the following when performing an update:

* Before updating {trserver}, ensure that all the {tragent}s in the
environment are supported by the target version. For more information,
see section <<sec-trento-compatibility-matrix>>.
* When updating {trento} to version 2.4 or higher, the admin password
may need to be adjusted to follow the rules described in the User
Management section.

In a {k8s} deployment, you can use Helm to update {trserver}:

====
[source,bash]
----
helm upgrade \
   --install trento-server oci://registry.suse.com/trento/trento-server \
   --set global.trentoWeb.origin=TRENTO_SERVER_HOSTNAME \
   --set trento-web.adminUser.password=ADMIN_PASSWORD \
   ...
        
----
====

If you have configured/enabled options, the {helm} command must be adjusted accordingly. In this case, consider the following:

* If you are using a version of Helm lower than 3.8.0, you need to set `HELM_EXPERIMENTAL_OCI=1` in front of the `helm` command.
* When updating {trento} to version 2.0.0 or higher, an additional flag
must be set in the Helm command:
+
====
[source,bash]
----
helm upgrade \
   --install trento-server oci://registry.suse.com/trento/trento-server \
   --set global.trentoWeb.origin=TRENTO_SERVER_HOSTNAME \
   --set trento-web.adminUser.password=ADMIN_PASSWORD \
   --set rabbitmq.auth.erlangCookie=$(openssl rand -hex 16)
        
----
====
+
* When updating {trento} to version 2.3 or higher, a new API key is
generated and the configuration of all registered {tragent}s must be
updated accordingly.
* When updating to version 3.1 or higher, connection to {prometheus} requires authentication. You must configure authentication to continue using {prometheus}.

In a systemd deployment, you can use zypper to update {trserver}:

====
[source,bash]
----
 zypper refresh
 zypper update trento-web
 zypper update trento-wanda
 systemctl restart trento-web
 systemctl restart trento-wanda     
----
====
