include::product-attributes.adoc[]

[[sec-enabling-email-alerts]]
=== Enabling email alerts
:revdate: 2026-09-24

The email alerting feature notifies the {sap} Basis administrator about important changes in the {sap} Landscape being monitored by {trento}.

Examples of reported events include the following:

* Host agent stopped reporting
* Cluster aggregated health changed to critical
* Database aggregated health changed to critical
* {sap} System aggregated health changed to critical

The email alerting feature is disabled by default. You can configure it either through the {tr_web} console or at the deployment level. 

Both methods require the following information:

SMTP Server::
The SMTP server designated to send email alerts.

SMTP Port::
Port on the SMTP server.

SMTP User::
User name to access the SMTP server.

SMTP Password::
Password to access the SMTP server.

Alert Sender::
Sender email for alert notifications.

Alert Recipient::
Email address to receive alert notifications.

[NOTE]
====
If you specify any email settings through your deployment configuration, the Web-based email configuration is disabled.
====

[[email-alerts-web]]
==== Configuring email alerts in the {tr_web} console

You can manage your email alerting configuration directly within the {tr_web} console. To do this, you must have the `all:settings` permission.

. In the left sidebar of the {tr_web} console, click *Settings*.
. In the *Email Alerts* section, click *Edit Settings*.
. Toggle *Send Email Alerts* to turn the feature on.
. Enter your SMTP server details, sender and recipient addresses.
. Click *Save Settings*.

[[email-alerts-k8s]]
==== Enabling email alerts on {k8s} deployments

For {k8s} deployments, use the `helm upgrade` command to enable email alerts:

[source,bash]
----
helm upgrade \
   --install trento-server oci://registry.suse.com/trento/trento-server \
   --set trento-web.alerting.enabled=true \
   --set trento-web.alerting.smtpServer=YOUR_SMTP_SERVER \
   --set trento-web.alerting.smtpPort=YOUR_SMTP_PORT \
   --set trento-web.alerting.smtpUser=YOUR_SMTP_USER \
   --set trento-web.alerting.smtpPassword=YOUR_SMTP_PASSWORD \
   --set trento-web.alerting.sender=YOUR_ALERT_SENDER \
   --set trento-web.alerting.recipient=YOUR_ALERT_RECIPIENT
   ...
----

[[email-alerts-systemd]]
==== Enabling email alerts on systemd deployments

For systemd deployments, perform the following steps:

. Enable and configure alerting by adding the following variables in `/etc/trento/trento-web`:
+
[source,bash]
----
# /etc/trento/trento-web
ENABLE_ALERTING=true
ALERT_SENDER=YOUR_ALERT_SENDER
ALERT_RECIPIENT=YOUR_ALERT_RECIPIENT
SMTP_SERVER=YOUR_SMTP_SERVER
SMTP_PORT=YOUR_SMTP_PORT
SMTP_USER=YOUR_SMTP_USER
SMTP_PASSWORD=YOUR_SMTP_PASSWORD
----

. Restart the service for the changes to take effect:
+
[source,bash]
----
systemctl restart trento-web
----

[[email-alerts-test]]
==== Testing your email alert configuration

You can verify your configuration by using the *Send Test Email* feature in the {tr_web} console.

You must have the `all:settings` permission to use this feature.

. In the left sidebar of the {tr_web} console, click *Settings*.
. In the *Email Alerts* section, click *Send Test Email*.
+
[NOTE]
====
If alerting is disabled or not configured, this button is unavailable.
====
+
A notification appears on the screen to inform you if the email delivery succeeded or failed.

The system also records the test results in the activity log. Successful tests are logged with an `info` severity, while failed tests are logged as `critical`.

If a test fails, you can check the `"reason"` field in the activity log metadata for troubleshooting details. See <<sec-activity-log-entries>> for how to view this metadata inside the *Activity Details* window.
