include::product-attributes.adoc[]

[[sec-trento-requirements]]
== Requirements
:revdate: 2026-01-08

This section describes requirements for the {trserver} and its {tragent}s, as well as the {sap} systems and clusters that we want to monitor in the backend environment. 

[[sec-trento-server-requirements]]
=== {trserver} requirements

Running all the {trserver} components requires a minimum of 4 GB of RAM, two CPU cores and 64 GB of storage. When using K3s, such storage should be provided under `/var/lib/rancher/k3s`.

{trento} is based on event-driven technology. Registered events are stored in a {postgresql} database with a default retention period of 10 days. For each host registered with {trento}, you need to allocate at least 1.5GB of space in the {postgresql} database.

{trserver} supports different deployment scenarios: {k8s} and systemd. A {k8s}-based deployment of {trserver} is cloud-native and OS-agnostic. It can be performed on the following services:

* RKE2
* a {k8s} service in a cloud provider
* any other CNCF-certified {k8s} running on x86_64 architecture

A production-ready {k8s}-based deployment of {trserver} requires {k8s} knowledge. The Helm chart is intended to be used by customers without in-house {k8s} expertise, or as a way to try {trento} with a minimum of effort. However, Helm chart delivers a basic deployment of the {trserver} with all the components running on a single node of the cluster.

[[sec-trento-agent-requirements]]
=== {tragent} requirements

The resource footprint of the {tragent} is designed to not impact the performance of the host it runs on.

The {tragent} component needs to interact with several low-level system components that are part of the {sles4sap} distribution.

The hosts must have unique machine identifiers (ids) in order to be registered in Trento. This means that if a host in your environment is built as a clone of another one, make sure to change the machine's identifier as part of the cloning process before starting the {tragent} on it.

Similarly, the clusters must have unique authkeys in order to be registered in {trento}.

[[sec-trento-network-requirements]]
=== Network requirements

* Required inbound connectivity:
** From any {tragent} host to {trserver} at port TCP/80 (HTTP), or TCP/443 (HTTPS) if SSL is enabled.
** From any {tragent} host to {trserver} at port TCP/5672 (Advanced Message Queuing Protocol or AMQP)
** From the user network to {trserver} at port TCP/80 (HTTP), or TCP/443 (HTTPS) if SSL is enabled.
** If the {tr_mcp} is installed and enabled:
*** For a {k8s} deployment, from the MCP client to the {trserver} ingress at TCP/80 or TCP/443. Internally, the MCP Server Pod uses TCP/{tr_mcp_default_port} and TCP/8080 if the health check is enabled.
*** For a systemd deployment, from the user network to {tr_mcp} at TCP/{tr_mcp_default_port}.
** Optionally: from the user network to {trserver} at ports TCP/4000, TCP/4001 and TCP/8080 (health checks for web, wanda and MCP, respectively).
** From Prometheus server, when it exists, to each {tragent} host at the port used by the Node Exporter.

[[sec-trento-installation-prerequisites]]
=== Installation prerequisites

* *{trserver}* For a {k8s}-based deployment, you must have access to {suse} public registry for the deployment of {trserver} containers. For a systemd deployment, you must have a registered {sles4sap} 15 (SP4 or higher) or {sles4sap} 16.0 distribution.
* *{tragent}s* A registered {sles4sap} 15 (SP3 or higher) distribution.

[[sec-sap-requirements]]
=== {sap} requirements

An {sap} system must run on a HANA database to be discovered by {trento}. In addition, the parameter `dbs/hdb/dbname` must be set in the DEFAULT profile of the {sap} system to the correct database (tenant) name.

The agent must be installed in all the hosts that are part of the SAP system architecture. Particularly:

* the host where the ASCS instance is running
* the host where the ERS instance, if it exists, is running
* all the hosts where an application server instance is running
* all the database hosts
