include::product-attributes.adoc[]

[[sec-systemd-deployment]]
=== systemd deployment
:revdate: 2025-06-11

A systemd-based installation of the {trento} Server using RPM packages can be performed manually on the latest supported versions of {sles4sap}, from 15 SP4 up to 16. For installations on service packs other than the current one, make sure to update the repository address as described in the relevant notes throughout this guide.

*Supported versions*:

* {sles4sap} 15: SP4–SP7
* {sles4sap} 16

==== List of dependencies

* https://nginx.org/en/[NGINX]
* https://www.postgresql.org/[PostgreSQL]
* https://prometheus.io/[Prometheus] (optional)
* https://rabbitmq.com/[RabbitMQ]

==== Install {trento} dependencies

===== Install Prometheus (Optional)

https://prometheus.io/[Prometheus] is not required to run {trento}, but it is highly recommended. When enabled, {trento} can display performance charts for each host, showing useful metrics such as CPU load and memory usage.

[NOTE]
====
If you choose not to install Prometheus, set `+CHARTS_ENABLED+` to
`+false+` in the {trento} web RPM configuration file stored in
`+/etc/trento/trento-web+`. To use an existing Prometheus installation, set `+CHARTS_ENABLED+` to
`+true+` 
====

====== Choose a Prometheus Setup Option

* <<prometheus-existing-installation, Use an existing Prometheus installation>>  
* <<prometheus-packagehub, Install Prometheus from the *unsupported* PackageHub repository>>


[[prometheus-existing-installation]]
====== Use an existing Prometheus installation

Minimal required Prometheus version is *2.28.0*.

[[prometheus-packagehub]]
====== Install Prometheus from the *unsupported* PackageHub repository

Prometheus is available for installation from the SUSE https://packagehub.suse.com/[PackageHub]  repository.
PackageHub packages are tested by SUSE but are not officially supported as part of the {sles4sap} base product.

. Enable the PackageHub repository (replace `x.x` with the version of your operating system, for example `15.7` or `16.0`):
+
[source,bash]
----
SUSEConnect --product PackageHub/x.x/x86_64
----
+
. Create the Prometheus user and group:
+
[source,bash]
----
groupadd --system prometheus
useradd -s /sbin/nologin --system -g prometheus prometheus
----
. Install Prometheus using Zypper:
+
[source,bash]
----
zypper in golang-github-prometheus-prometheus
----
. Configure Prometheus for Trento
+
Replace or update the existing configuration at +/etc/prometheus/prometheus.yml+ with:
+
[source,yaml]
----
global:
  scrape_interval: 30s
  evaluation_interval: 10s

scrape_configs:
  - job_name: "http_sd_hosts"
    honor_timestamps: true
    scrape_interval: 30s
    scrape_timeout: 30s
    scheme: http
    follow_redirects: true
    http_sd_configs:
      - follow_redirects: true
        refresh_interval: 1m
        url: http://localhost:4000/api/prometheus/targets
----
+
[NOTE]
====
+localhost:4000+ in +http://localhost:4000/api/prometheus/targets+
refers to the location where {trento} web service is running.
====
. Enable and start the Prometheus service:
+
[source,bash]
----
systemctl enable --now prometheus
----
. If firewalld is running, allow Prometheus to be accessible and add an exception to firewalld:
+
[source,bash]
----
firewall-cmd --zone=public --add-port=9090/tcp --permanent
firewall-cmd --reload
----

===== Install PostgreSQL

The current instructions are tested with the following PostgreSQL
versions:

[cols="2,2", options="header"]
|===
| {sles4sap} | PostgreSQL Version

| 15 SP4 | 14.10
| 15 SP5 | 15.5
| 15 SP6 | 16.9
| 15 SP7 | 17.5
| 16.0   | 17.6
|===

Using a different version of PostgreSQL may require different steps or
configurations, especially when changing the major number. For more
details, refer to the official
https://www.postgresql.org/docs/[PostgreSQL documentation].

. Install PostgreSQL server:
+
[source,bash]
----
zypper in postgresql-server
----
. Enable and start PostgreSQL server:
+
[source,bash]
----
systemctl enable --now postgresql
----

====== Configure PostgreSQL

. Start `+psql+` with the `+postgres+` user to open a connection to the
database:
+
[source,bash]
----
su - postgres
psql
----
. Initialize the databases in the `+psql+` console:
+
[source,sql]
----
CREATE DATABASE wanda;
CREATE DATABASE trento;
CREATE DATABASE trento_event_store;
----
. Create the users:
+
[source,sql]
----
CREATE USER wanda_user WITH PASSWORD 'wanda_password';
CREATE USER trento_user WITH PASSWORD 'web_password';
----
. Grant required privileges to the users and close the connection:
+
[source,sql]
----
\c wanda
GRANT ALL ON SCHEMA public TO wanda_user;
\c trento
GRANT ALL ON SCHEMA public TO trento_user;
\c trento_event_store;
GRANT ALL ON SCHEMA public TO trento_user;
\q
----
+
You can exit from the `+psql+` console and `+postgres+` user.
. Allow the PostgreSQL database to receive connections to the respective
databases and users. To do this, add the following to
`+/var/lib/pgsql/data/pg_hba.conf+`:
+
[source,bash]
----
host   wanda                      wanda_user    0.0.0.0/0     scram-sha-256
host   trento,trento_event_store  trento_user   0.0.0.0/0     scram-sha-256
----
+
[NOTE]
====
The `+pg_hba.conf+` file works sequentially. This means that the rules
on the top have preference over the ones below. The example above shows
a permissive address range. So for this to work, the entires must be
written at the top of the `+host+` entries. For further information,
refer to the
https://www.postgresql.org/docs/current/auth-pg-hba-conf.html[pg_hba.conf]
documentation.
====
. Allow PostgreSQL to bind on all network interfaces in
`+/var/lib/pgsql/data/postgresql.conf+` by changing the following line:
+
[source,bash]
----
listen_addresses = '*'
----
. Restart PostgreSQL to apply the changes:
+
[source,bash]
----
systemctl restart postgresql
----

===== Install RabbitMQ

. Install RabbitMQ server:
+
[source,bash]
----
zypper install rabbitmq-server
----
. Allow connections from external hosts by modifying
`+/etc/rabbitmq/rabbitmq.conf+`, so the {trento}-agent can reach RabbitMQ:
+
[source,ini files]
----
listeners.tcp.default = 5672
----
. If firewalld is running, add a rule to firewalld:
+
[source,bash]
----
firewall-cmd --zone=public --add-port=5672/tcp --permanent;
firewall-cmd --reload
----
. Enable the RabbitMQ service:
+
[source,bash]
----
systemctl enable --now rabbitmq-server
----

====== Configure RabbitMQ

To configure RabbitMQ for a production system, follow the official
suggestions in the
https://www.rabbitmq.com/production-checklist.html[RabbitMQ guide].

. Create a new RabbitMQ user:
+
[source,bash]
----
rabbitmqctl add_user trento_user trento_user_password
----
. Create a virtual host:
+
[source,bash]
----
rabbitmqctl add_vhost vhost
----
. Set permissions for the user on the virtual host:
+
[source,bash]
----
rabbitmqctl set_permissions -p vhost trento_user ".*" ".*" ".*"
----

==== Install {trento} using RPM packages

The `trento-web` and `trento-wanda` packages are available by default on supported {sles4sap} distributions.

Install {trento} web, wanda and checks:

[source,bash]
----
zypper install trento-web trento-wanda
----

===== Create the configuration files

Both services depend on respective configuration files. They must be
placed in `+/etc/trento/trento-web+` and `+/etc/trento/trento-wanda+`
respectively, and examples of how to modify them are available in
`+/etc/trento/trento-web.example+` and `+/etc/trento/trento-wanda.example+`.

[NOTE]
====
You can create the content of the secret variables such as
`SECRET_KEY_BASE`, `ACCESS_TOKEN_ENC_SECRET` and `REFRESH_TOKEN_ENC_SECRET` using `openssl`:

[source,bash]
----
openssl rand -out /dev/stdout 48 | base64
----

Also ensure that a valid hostname, FQDN, or IP address is configured in
`TRENTO_WEB_ORIGIN` when using HTTPS.
Otherwise, WebSocket connections will fail, preventing real-time updates
in the web interface.
====

===== trento-web configuration

====
[source,bash]
----
# /etc/trento/trento-web
AMQP_URL=amqp://trento_user:trento_user_password@localhost:5672/vhost
DATABASE_URL=ecto://trento_user:web_password@localhost/trento
EVENTSTORE_URL=ecto://trento_user:web_password@localhost/trento_event_store
ENABLE_ALERTING=false
CHARTS_ENABLED=true
PROMETHEUS_URL=http://localhost:9090
ADMIN_USER=admin
ADMIN_PASSWORD=trentodemo
ENABLE_API_KEY=true
PORT=4000
TRENTO_WEB_ORIGIN=trento.example.com
SECRET_KEY_BASE=some-secret
ACCESS_TOKEN_ENC_SECRET=some-secret
REFRESH_TOKEN_ENC_SECRET=some-secret
CHECKS_SERVICE_BASE_URL=/wanda
OAS_SERVER_URL=https://trento.example.com
----
====

The `ADMIN_PASSWORD` variable must comply with the following rules:

* At least 8 characters
* Must not contain 3 consecutive repeated numbers or letters (e.g., 111 or aaa)
* Must not contain 4 consecutive sequential numbers or letters (e.g., 1234, abcd, ABCD)

The `CHARTS_ENABLED` variable enable {trento} to display performance charts for each host, showing useful metrics such as CPU load and memory usage.
`CHARTS_ENABLED` *must* be set to `false`, if Prometheus is not installed or you do not want to use {trento}'s charts functionality.

The `ENABLE_ALERTING` enables the 
https://www.trento-project.io/docs/web/Alerting/alerting.html[alerting system to receive email notifications]. Set `ENABLE_ALERTING` to `true` and add additional variables to the `/etc/trento/trento-web`, to enable the feature.

====
[source,bash]
----
# /etc/trento/trento-web
ENABLE_ALERTING=true
ALERT_SENDER=<<SENDER_EMAIL_ADDRESS>>
ALERT_RECIPIENT=<<RECIPIENT_EMAIL_ADDRESS>>
SMTP_SERVER=<<SMTP_SERVER_ADDRESS>>
SMTP_PORT=<<SMTP_PORT>>
SMTP_USER=<<SMTP_USER>>
SMTP_PASSWORD=<<SMTP_PASSWORD>>
----
====

===== trento-wanda configuration

====
[source,bash]
----
# /etc/trento/trento-wanda
CORS_ORIGIN=http://localhost
AMQP_URL=amqp://trento_user:trento_user_password@localhost:5672/vhost
DATABASE_URL=ecto://wanda_user:wanda_password@localhost/wanda
PORT=4001
SECRET_KEY_BASE=some-secret
OAS_SERVER_URL=https://trento.example.com/wanda
AUTH_SERVER_URL=http://localhost:4000
----
====

===== Start the services

[NOTE]
====
In some {sles4sap} environments, SELinux may be enabled and set to *enforcing* mode by default.  
If {trento} services fail to start or show permission-related errors, check the SELinux status:

[source,bash]
----
getenforce
----

If SELinux is set to *enforcing*, you can switch it to *permissive* mode either temporarily or permanently:

* **Temporary change (until reboot):**
+
[source,bash]
----
setenforce 0
----

* **Permanent change (persists after reboot):**
+
Edit `/etc/selinux/config` and set:
+
[source]
----
SELINUX=permissive
----
+

====

Enable and start the services:

[source,bash]
----
systemctl enable --now trento-web trento-wanda
----

===== Monitor the services

Use `+journalctl+` to check if the services are up and running
correctly. For example:

[source,bash]
----
journalctl -fu trento-web
----

[[validate-the-health-status-of-trento-web-and-wanda]]
==== Check the health status of trento web and wanda

You can check if {trento} web and wanda services function correctly by
accessing accessing the `+healthz+` and `+readyz+` API.

. Check {trento} web health status using `+curl+`:
+
[source,bash]
----
curl http://localhost:4000/api/readyz
----
+
[source,bash]
----
curl http://localhost:4000/api/healthz
----
. Check {trento} wanda health status using `+curl+`:
+
[source,bash]
----
curl http://localhost:4001/api/readyz
----
+
[source,bash]
----
curl http://localhost:4001/api/healthz
----

If {trento} web and wanda are ready, and the database connection is set up
correctly, the output should be as follows:

====
[source,bash]
----
{"ready":true}{"database":"pass"}
----
====


==== Install and configure NGINX

. Install NGINX package:
+
[source,bash]
----
zypper install nginx
----
. If firewalld is running, add firewalld rules for HTTP and HTTPS:
+
[source,bash]
----
firewall-cmd --zone=public --add-service=https --permanent
firewall-cmd --zone=public --add-service=http --permanent
firewall-cmd --reload
----
. Start and enable NGINX:
+
[source,bash]
----
systemctl enable --now nginx
----
. Create a configuration file for {trento}:
+
[source,bash]
----
vim /etc/nginx/conf.d/trento.conf
----
. Add the following configuration to `+/etc/nginx/conf.d/trento.conf+`:
+
====
[source,bash]
----
map $http_upgrade $connection_upgrade {
  default upgrade;
  '' close;
}

upstream web {
  server 127.0.0.1:4000 max_fails=5 fail_timeout=60s;
}

upstream wanda {
  server 127.0.0.1:4001 max_fails=5 fail_timeout=60s;
}

server {
    # Redirect HTTP to HTTPS
    listen 80;
    server_name trento.example.com;
    return 301 https://$host$request_uri;
}

server {
    server_name trento.example.com;
    listen 443 ssl;

    ssl_certificate /etc/nginx/ssl/certs/trento.crt;
    ssl_certificate_key /etc/ssl/private/trento.key;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers 'ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384';
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;

    # Wanda rule
    location /wanda/  {
        allow all;

        # Proxy Headers
        proxy_http_version 1.1;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_set_header X-Cluster-Client-Ip $remote_addr;

        # Important Websocket Bits!
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        # Add final slash to replace the location path value by the value in proxy_pass
        # https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_pass
        proxy_pass http://wanda/;
    }

    # Web rule
    location / {
        # this endpoint should not be accessible publicly
        # it is internally used by wanda to introspect access tokens and personal access tokens
        location /api/session/token/introspect {
            deny all;
            return 404;
        }

        allow all;

        # Proxy Headers
        proxy_http_version 1.1;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_set_header X-Cluster-Client-Ip $remote_addr;

        # The Important Websocket Bits!
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_pass http://web;
    }
}
----
====

==== Prepare SSL certificate for NGINX

Create or provide a certificate for https://nginx.org/en/[NGINX] to
enable SSL for {trento}.

[[option-1-creating-a-self-signed-certificate]]
===== Create a self-signed certificate

. Generate a self-signed certificate:
+
[NOTE]
====
Adjust `+subjectAltName = DNS:trento.example.com+` by replacing
`+trento.example.com+` with your domain and change the value `+5+` to
the number of days for which you need the certificate to be valid. For
example, `+-days 365+` for one year.
====
+
[source,bash]
----
openssl req -newkey rsa:2048 --nodes -keyout trento.key -x509 -days 5 -out trento.crt -addext "subjectAltName = DNS:trento.example.com"
----
. Copy the generated `+trento.key+` to a location accessible by NGINX:
+
[source,bash]
----
cp trento.key /etc/ssl/private/trento.key
----
. Create a directory for the generated `+trento.crt+` file. The
directory must be accessible by NGINX:
+
[source,bash]
----
mkdir -p /etc/nginx/ssl/certs/
----
. Copy the generated `+trento.crt+` file to the created directory:
+
[source,bash]
----
cp trento.crt /etc/nginx/ssl/certs/trento.crt
----
. Check the NGINX configuration:
+
[source,bash]
----
nginx -t
----
+
If the configuration is correct, the output should be as follows:
+
[source,bash]
----
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
----
+
If there are issues with the configuration, the output indicates what
needs to be adjusted.
+
. Enable NGINX:
+
[source,bash]
----
systemctl restart nginx
----

[[option-2-using-lets-encrypt-for-a-signed-certificate-using-packagehub-repository]]
===== Create a signed certificate with Let's Encrypt using PackageHub repository


. Enable the PackageHub repository (replace `x.x` with your OS version, for example `15.7` or `16.0`):
+
[source,bash]
----
SUSEConnect --product PackageHub/x.x/x86_64
zypper refresh
----
+
. Install Certbot and its NGINX plugin:
+
[NOTE]
====
Service Packs include version-specific Certbot NGINX plugin packages, for example `+python311-certbot-nginx+` or `+python3-certbot-nginx+`. Install the package available in the Service Pack you currently use.
====
+
[source,bash]
----
zypper install certbot python311-certbot-nginx
----
. Obtain a certificate and configure NGINX with Certbot:
+
[NOTE]
====
Replace `+example.com+` with your domain. For more information, refer to
https://certbot.eff.org/instructions?ws=nginx&os=leap[Certbot
instructions for NGINX]
====
+
[source,bash]
----
certbot --nginx -d trento.example.com -d trento.example.com
----
+
[NOTE]
====
Certbot certificates are valid for 90 days. Refer to the above link for
details on how to renew certificates.
====

==== Accessing the trento-web UI

Pin the browser to `+https://trento.example.com+`. You should be able to
login using the credentials specified in the `+ADMIN_USER+` and
`+ADMIN_PASSWORD+` environment variables.
