include::product-attributes.adoc[]

[[sec-systemd-deployment]]
==== systemd deployment
:revdate: 2026-08-28

A systemd-based installation of the {trserver} using RPM packages can be performed manually on the latest supported versions of {sles4sap}, from 15 SP4 up to 16. For installations on service packs other than the current one, make sure to update the repository URL as described in the relevant notes throughout this guide.

===== List of dependencies

* https://nginx.org/en/[NGINX]
* https://www.postgresql.org/[PostgreSQL]
* https://rabbitmq.com/[RabbitMQ]

===== Install {trento} dependencies

====== Install PostgreSQL

The current instructions are tested with the following PostgreSQL
versions:

[cols="2,2", options="header"]
|===
| {sles4sap} | PostgreSQL Version

| 15 SP4 | 14.10
| 15 SP5 | 15.5
| 15 SP6 | 16.9
| 15 SP7 | 17.5
| 16.0   | 17.6
|===

Using a different version of PostgreSQL may require different steps or
configurations, especially when changing the major number. For more
details, refer to the official
https://www.postgresql.org/docs/[PostgreSQL documentation].

. Install PostgreSQL server:
+
[source,bash,subs="attributes"]
----
{sudo} zypper install postgresql-server
----

. Enable and start PostgreSQL server:
+
[source,bash,subs="attributes"]
----
{sudo} systemctl enable --now postgresql
----

====== Configure PostgreSQL

. Start `+psql+` with the `+postgres+` user to open a connection to the
database:
+
[source,bash,subs="attributes"]
----
{sudo} su - postgres
psql
----

. Initialize the databases in the `+psql+` console:
+
[source,sql]
----
CREATE DATABASE wanda;
CREATE DATABASE trento;
CREATE DATABASE trento_event_store;
----

. Create the users:
+
[NOTE]
====
The values `WANDA_USER`, `WANDA_PASSWORD`, `TRENTO_USER`, and `WEB_PASSWORD` are placeholders. Replace them with your own secure values before running these commands.
====
+
[source,sql]
----
CREATE USER WANDA_USER WITH PASSWORD 'WANDA_PASSWORD';
CREATE USER TRENTO_USER WITH PASSWORD 'WEB_PASSWORD';
----

. Grant required privileges to the users and close the connection:
+
[source,sql]
----
\c wanda
GRANT ALL ON SCHEMA public TO WANDA_USER;
\c trento
GRANT ALL ON SCHEMA public TO TRENTO_USER;
\c trento_event_store
GRANT ALL ON SCHEMA public TO TRENTO_USER;
\q
----

. Exit the `+postgres+` user session:
+
[source,sql]
----
exit
----

. Allow the PostgreSQL database to receive connections to the respective
databases and users. To do this, add the following to
`+/var/lib/pgsql/data/pg_hba.conf+`:
+
[IMPORTANT]
====
The `+pg_hba.conf+` file works sequentially. This means that the rules
on the top have preference over the ones below. The following example shows
a permissive address range. So for this to work, the new entries must be
written at the top of the `+host+` section. For further information,
refer to the
https://www.postgresql.org/docs/current/auth-pg-hba-conf.html[pg_hba.conf]
documentation.
====
+
[source,text]
----
host   wanda                      WANDA_USER    0.0.0.0/0     scram-sha-256
host   trento,trento_event_store  TRENTO_USER   0.0.0.0/0     scram-sha-256
----

. Allow PostgreSQL to bind on all network interfaces in
`+/var/lib/pgsql/data/postgresql.conf+` by changing the following line:
+
[source,ini]
----
listen_addresses = '*'
----

. Restart PostgreSQL to apply the changes:
+
[source,bash,subs="attributes"]
----
{sudo} systemctl restart postgresql
----

====== Install RabbitMQ

. Install RabbitMQ server:
+
[source,bash,subs="attributes"]
----
{sudo} zypper install rabbitmq-server
----

. Allow connections from external hosts by modifying
`+/etc/rabbitmq/rabbitmq.conf+`, so the {trento}-agent can reach RabbitMQ:
+
[source,ini]
----
listeners.tcp.default = 5672
----

. If firewalld is running, add a rule to firewalld:
+
[source,bash,subs="attributes"]
----
{sudo} firewall-cmd --zone=public --add-port=5672/tcp --permanent
{sudo} firewall-cmd --reload
----

. Enable the RabbitMQ service:
+
[source,bash,subs="attributes"]
----
{sudo} systemctl enable --now rabbitmq-server
----

====== Configure RabbitMQ

To configure RabbitMQ for a production system, follow the official
suggestions in the
https://www.rabbitmq.com/production-checklist.html[RabbitMQ guide].

. Create a new RabbitMQ user:
+
[NOTE]
====
The values `TRENTO_USER` and `TRENTO_USER_PASSWORD` are placeholders. Replace them with your own secure values before running these commands.
====
+
[source,bash,subs="attributes"]
----
{sudo} rabbitmqctl add_user TRENTO_USER TRENTO_USER_PASSWORD
----

. Create a virtual host:
+
[source,bash,subs="attributes"]
----
{sudo} rabbitmqctl add_vhost vhost
----

. Set permissions for the user on the virtual host:
+
[source,bash,subs="attributes"]
----
{sudo} rabbitmqctl set_permissions -p vhost TRENTO_USER ".*" ".*" ".*"
----

===== Install {trento} using RPM packages

The `trento-web` and `trento-wanda` packages are available by default on supported {sles4sap} distributions.

Install {trento} web, wanda and checks:

[source,bash,subs="attributes"]
----
{sudo} zypper install trento-web trento-wanda
----

====== Create the configuration files

Both services depend on respective configuration files. They must be
placed in `+/etc/trento/trento-web+` and `+/etc/trento/trento-wanda+`
respectively, and examples of how to modify them are available in
`+/etc/trento/trento-web.example+` and `+/etc/trento/trento-wanda.example+`.

[NOTE]
====
You can create the content of the secret variables such as
`SECRET_KEY_BASE`, `ACCESS_TOKEN_ENC_SECRET` and `REFRESH_TOKEN_ENC_SECRET` using `openssl`:

[source,bash]
----
openssl rand -out /dev/stdout 48 | base64
----
====

. Create the `/etc/trento/trento-web` configuration file. For example:
+
[NOTE]
====
The values `TRENTO_USER`, `TRENTO_USER_PASSWORD`, and `WEB_PASSWORD` are placeholders. Replace them with your own secure values before running these commands.
====
+
[source,bash]
----
# /etc/trento/trento-web
AMQP_URL=amqp://TRENTO_USER:TRENTO_USER_PASSWORD@localhost:5672/vhost
DATABASE_URL=ecto://TRENTO_USER:WEB_PASSWORD@localhost/trento
EVENTSTORE_URL=ecto://TRENTO_USER:WEB_PASSWORD@localhost/trento_event_store
ENABLE_ALERTING=false
CHARTS_ENABLED=false
ADMIN_USER=admin
ADMIN_PASSWORD=trentodemo
ENABLE_API_KEY=true
PORT=4000
LOG_LEVEL=info
TRENTO_WEB_ORIGIN=trento.example.com
SECRET_KEY_BASE=some-secret
ACCESS_TOKEN_ENC_SECRET=some-secret
REFRESH_TOKEN_ENC_SECRET=some-secret
CHECKS_SERVICE_BASE_URL=/wanda
OAS_SERVER_URL=https://trento.example.com
----

** The `LOG_LEVEL` sets how much detail {tr_web} writes to the log. The default value is `info`. For more information, see <<sec-configuring-log-levels>>.

** The `TRENTO_WEB_ORIGIN` configures internal functionalities such as the interactive API portal, websockets, or certificate generation.
+
[IMPORTANT]
====
Ensure that a valid hostname, FQDN, or IP address is configured in
`TRENTO_WEB_ORIGIN` when using HTTPS.
Otherwise, websocket connections will fail, preventing real-time updates
in the web interface.
====

** The `ADMIN_PASSWORD` variable must meet the following requirements:
	
*** Minimum of 8 characters
*** The password  not contain 3 consecutive identical numbers or letters (for example, 111 or aaa)
*** The password must not contain 4 consecutive  numbers or letters (for example, 1234, abcd, ABCD)


** The `ENABLE_ALERTING` enables the 
https://www.trento-project.io/docs/web/Alerting/alerting.html[alerting system to receive email notifications]. Set `ENABLE_ALERTING` to `true` and add additional variables to the `/etc/trento/trento-web` to enable the feature:
+
[source,bash]
----
# /etc/trento/trento-web
ENABLE_ALERTING=true
ALERT_SENDER=<<SENDER_EMAIL_ADDRESS>>
ALERT_RECIPIENT=<<RECIPIENT_EMAIL_ADDRESS>>
SMTP_SERVER=<<SMTP_SERVER_ADDRESS>>
SMTP_PORT=<<SMTP_PORT>>
SMTP_USER=<<SMTP_USER>>
SMTP_PASSWORD=<<SMTP_PASSWORD>>
----

. Create the `/etc/trento/trento-wanda` configuration file. For example:
+
[NOTE]
====
The values `WANDA_USER`, `WANDA_PASSWORD`, `TRENTO_USER`, and `TRENTO_USER_PASSWORD` are placeholders. Replace them with your own secure values before running these commands.
====
+
[source,bash]
----
# /etc/trento/trento-wanda
CORS_ORIGIN=http://localhost
AMQP_URL=amqp://TRENTO_USER:TRENTO_USER_PASSWORD@localhost:5672/vhost
DATABASE_URL=ecto://WANDA_USER:WANDA_PASSWORD@localhost/wanda
PORT=4001
LOG_LEVEL=info
SECRET_KEY_BASE=some-secret
OAS_SERVER_URL=https://trento.example.com/wanda
AUTH_SERVER_URL=http://localhost:4000
----

. Secure the configuration files.
+
To protect sensitive information, the configuration files must have `600` permissions so that only the `root` user can read them:
+
[source,bash,subs="attributes"]
----
{sudo} chmod 600 /etc/trento/trento-web
{sudo} chmod 600 /etc/trento/trento-wanda
----

====== Start the services

[NOTE]
====
In some {sles4sap} environments, SELinux may be enabled and set to *enforcing* mode by default.  
If {trento} services fail to start or show permission-related errors, check the SELinux status:

[source,bash,subs="attributes"]
----
{sudo} getenforce
----

If SELinux is set to *enforcing*, switch it to *permissive* mode either temporarily or permanently:

* **Temporary change (until reboot):**
+
[source,bash,subs="attributes"]
----
{sudo} setenforce 0
----

* **Permanent change (persists after reboot):**
+
Edit `/etc/selinux/config` and set:
+
[source,ini]
----
SELINUX=permissive
----
====

Enable and start the services:

[source,bash,subs="attributes"]
----
{sudo} systemctl enable --now trento-web trento-wanda
----

====== Monitor the services

Use `+journalctl+` to check if the services are up and running
correctly. For example:

[source,bash,subs="attributes"]
----
{sudo} journalctl -fu trento-web
----

[[validate-the-health-status-of-trento-web-and-wanda]]
===== Check the health status of {tr_web} and {tr_wanda}

You can check if {tr_web} and {tr_wanda} services function correctly by
accessing the `+healthz+` and `+readyz+` API.

If {trento} web and wanda are ready, and the database connection is set up
correctly, the output should be as follows:

====
[source,bash]
----
{"ready":true}{"database":"pass"}
----
====

. Check {tr_web} health status using `+curl+`:
+
[source,bash]
----
curl http://localhost:4000/api/readyz
----
+
[source,bash]
----
curl http://localhost:4000/api/healthz
----
. Check {tr_wanda} health status using `+curl+`:
+
[source,bash]
----
curl http://localhost:4001/api/readyz
----
+
[source,bash]
----
curl http://localhost:4001/api/healthz
----

===== Install and configure NGINX

. Install NGINX package:
+
[source,bash,subs="attributes"]
----
{sudo} zypper install nginx
----
. If firewalld is running, add firewalld rules for HTTP and HTTPS:
+
[source,bash,subs="attributes"]
----
{sudo} firewall-cmd --zone=public --add-service=https --permanent
{sudo} firewall-cmd --zone=public --add-service=http --permanent
{sudo} firewall-cmd --reload
----
. Start and enable NGINX:
+
[source,bash,subs="attributes"]
----
{sudo} systemctl enable --now nginx
----
. Create a `+/etc/nginx/conf.d/trento.conf+` {trento} configuration file:
+
====
[source,bash]
----
map $http_upgrade $connection_upgrade {
  default upgrade;
  '' close;
}

upstream web {
  server 127.0.0.1:4000 max_fails=5 fail_timeout=60s;
}

upstream wanda {
  server 127.0.0.1:4001 max_fails=5 fail_timeout=60s;
}

server {
    # Redirect HTTP to HTTPS
    listen 80;
    server_name trento.example.com;
    return 301 https://$host$request_uri;
}

server {
    server_name trento.example.com;
    listen 443 ssl;

    ssl_certificate /etc/nginx/ssl/certs/trento.crt;
    ssl_certificate_key /etc/ssl/private/trento.key;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers 'ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384';
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;

    # Wanda rule
    location /wanda/  {
        allow all;

        # Proxy Headers
        proxy_http_version 1.1;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_set_header X-Cluster-Client-Ip $remote_addr;

        # Important Websocket Bits!
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        # Add final slash to replace the location path value by the value in proxy_pass
        # https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_pass
        proxy_pass http://wanda/;
    }

    # Web rule
    location / {
        # this endpoint should not be accessible publicly
        # it is internally used by wanda to introspect access tokens and personal access tokens
        location /api/session/token/introspect {
            deny all;
            return 404;
        }

        allow all;

        # Proxy Headers
        proxy_http_version 1.1;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_set_header X-Cluster-Client-Ip $remote_addr;

        # The Important Websocket Bits!
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_pass http://web;
    }
}
----
====

===== Prepare SSL certificate for NGINX

Create or provide a certificate for https://nginx.org/en/[NGINX] to
enable SSL for {trento}. Choose one of the following methods:

* To manually generate a self-signed certificate, see <<option-1-creating-a-self-signed-certificate>>.
* To automate obtaining a signed certificate with Let's Encrypt, see <<option-2-using-lets-encrypt-for-a-signed-certificate-using-packagehub-repository>>.
* To provide an existing signed certificate, you can use the procedure in <<option-1-creating-a-self-signed-certificate>>, skipping step 1 and adapting the remaining steps to use your own files.

[[option-1-creating-a-self-signed-certificate]]
====== Create a self-signed certificate

Manually generate a self-signed certificate and ensure it is trusted by the system.

. Generate a self-signed certificate:
+
[NOTE]
====
Adjust `+subjectAltName = DNS:trento.example.com+` by replacing
`+trento.example.com+` with your domain and change the value `+5+` to
the number of days for which you need the certificate to be valid. For
example, `+-days 365+` for one year.
====
+
[source,bash]
----
openssl req -newkey rsa:2048 --nodes -keyout trento.key -x509 -days 5 -out trento.crt -addext "subjectAltName = DNS:trento.example.com"
----

. Copy the generated `+trento.key+` to a location accessible by NGINX:
+
[source,bash,subs="attributes"]
----
{sudo} cp trento.key /etc/ssl/private/trento.key
----

. Create a directory for the generated `+trento.crt+` file. The
directory must be accessible by NGINX:
+
[source,bash,subs="attributes"]
----
{sudo} mkdir -p /etc/nginx/ssl/certs/
----

. Copy the generated `+trento.crt+` file to the created directory:
+
[source,bash,subs="attributes"]
----
{sudo} cp trento.crt /etc/nginx/ssl/certs/trento.crt
----

. Ensure the self-signed certificate is trusted:

.. Convert `trento.crt` to the PEM format:
+
[source,bash]
----
openssl x509 -in trento.crt -out trento.pem -outform PEM
----

.. Copy the certificate in PEM format to `/etc/pki/trust/anchors/`:
+
[source,bash,subs="attributes"]
----
{sudo} cp trento.pem /etc/pki/trust/anchors/
----

.. Run the `update-ca-certificates` command:
+
[source,bash,subs="attributes"]
----
{sudo} update-ca-certificates
----

. Check the NGINX configuration:
+
[source,bash,subs="attributes"]
----
{sudo} nginx -t
----
+
If the configuration is correct, the output should be as follows:
+
[source,bash]
----
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
----
+
If there are issues with the configuration, the output indicates what
needs to be adjusted.
. Enable NGINX:
+
[source,bash,subs="attributes"]
----
{sudo} systemctl restart nginx
----

[[option-2-using-lets-encrypt-for-a-signed-certificate-using-packagehub-repository]]
====== Create a signed certificate with Let's Encrypt using PackageHub repository

Automate obtaining a signed certificate with Let's Encrypt and configure NGINX to use it.

. Enable the PackageHub repository (replace `x.x` with your OS version, for example `15.7`):
+
[source,bash,subs="attributes"]
----
{sudo} SUSEConnect --product PackageHub/x.x/x86_64
{sudo} zypper refresh
----

. Find the Certbot NGINX plug-in package available in your current Service Pack:
+
[source,bash]
----
zypper search certbot-nginx
----
+
Example output:
+
[source,bash]
----
S  | Name                    | Summary                  | Type
---+-------------------------+--------------------------+--------
   | python313-certbot-nginx | Nginx plugin for Certbot | package
----

. Install Certbot and its NGINX plug-in. Use the specific package name returned in the output of the previous step. For example:
+
[source,bash,subs="attributes"]
----
{sudo} zypper install certbot python313-certbot-nginx
----

. Obtain a certificate and configure NGINX with Certbot:
+
[NOTE]
====
Replace `+trento.example.com+` with your domain. For more information, refer to
https://certbot.eff.org/instructions?ws=nginx&os=leap[Certbot
instructions for NGINX]
====
+
[source,bash,subs="attributes"]
----
{sudo} certbot --nginx -d trento.example.com
----
+
[NOTE]
====
Certbot certificates are valid for 90 days. Refer to the above link for
details on how to renew certificates.
====

===== Accessing the trento-web UI

Pin the browser to `+https://trento.example.com+`. You should be able to
login using the credentials specified in the `+ADMIN_USER+` and
`+ADMIN_PASSWORD+` environment variables.
