include::product-attributes.adoc[]

== Operations

Operations in {trento} are ruled by four principles:

. They are protected by permissions: only users with `operation:all` permissions are allowed to perform operations.
. The path in the UI to request an operation is a contextual one. For example, if you want to turn maintenance on in a cluster, the path that you will follow to request the operation will depend on the exact target. If you want to turn maintenance on in the entire cluster, you will request the operation from the Operation button at the top of the cluster details view. If you want to turn maintenance on in a particular node, you will do it from the burger menu in the right hand side of the corresponding node row. And if you want to turn maintenance on in a particular resource, you will do it from the burger menu in the right hand side of the corresponding resource row.
. One operation at a time on any given target. All operations on any given target (host, cluster, {sap} system, {hana} database) will be disabled as long as there is an operation running for that particular target.
. Operations are safeguarded by internal policies that prevent the user from executing them when such execution violates documented, well established best practices, even if the user has the required permissions. For example, if a user requests the stop of a {hana} database that is managed by a cluster, {trento} will forbid the operation and inform the user why. Each operation has different internal policies. They are listed further below when describing the different available operation use cases.

IMPORTANT: Internal policies are meant to prevent the user from carrying out basic operational mistakes but can not guarantee that an operation will cause no damage to the environment. The ultimate responsibility of executing an operation falls with the user.

Every operation request generates an entry in the activity log with a specific activity type. Following a successful operation request, {trento} tries to execute the operation. The completion of the operation, whether successful or not, is also recorded in the activity log with activity type Operation Completed and correlated to the request entry (see <<sec-activity-log>> for details). When an operation is not successful, {trento} restores the original state by rolling back the operation.

To prevent an endless execution in situations where, for example, an agent is not responding, every operation is time constrained by an internal timeout. Once the internal timeout is hit, the operation execution resets.

=== Host operations

For any registered host, the following operations are available in the corresponding details view:

* Apply {saptune} Solution. Enabled when an {sap} workload has been discovered in the host but there is no {saptune} solution applied yet. {trento} restricts the solutions available for selection based on the nature of the {sap} workload. If the {sap} workload is a {hana} instance, the choice will be between HANA and S4HANA-DESERVER . If the {sap} workload is an application instance, the choice will be between NETWEAVER and S4HANA-APPSERVER.
** Activity type: Host Operation Requested
** Internal policies: the {sap} workload must be stopped
** Internal timeout: 5m

* Change {saptune} Solution. Enabled when an {sap} workload has been discovered in the host and there is already an applied {saptune} solution. Same as with the apply operation, {trento} will restrict the solutions available for selection based on the nature of the {sap} workload.
** Activity type: Host Operation Requested
** Internal policies: the {sap} workload must be stopped
** Internal timeout: 5m

* Reboot Host. It schedules a reboot of the target host within a minute of the request time:
** Activity type: Host Operation Requested
** Internal policies:
*** If an {sap} workload has been discovered in the host, it must be stopped.
*** If the host is a cluster node, the {pace} service must be disabled at boot and stopped (the node must be offline node).
** Internal timeout: 5m

=== Cluster operations

Every time a user requests a cluster operation, {trento} checks the cluster state using `cs_clusterstate -i`. If the {tragent} cannot find the `cs_clusterstate` executable or it returns any state other than IDLE, the operation fails. This restriction has been implemented to ensure that a user cannot execute an operation while the cluster is in transition.

NOTE: The `cs_clusterstate` executable is delivered with the `ClusterTools2` package.

For any registered cluster, the following operations are available in the corresponding details view:

* At cluster level:
** Cluster maintenance. Enabled when at least one node in the cluster is online. It turns maintenance on or off in the cluster, depending on its current status.
*** Activity type: Cluster Operation Requested
*** Internal policies: not applicable
*** Internal timeout: 5m

* At node level:
** Node maintenance. Enabled when the node is online. It turns maintenance on or off in the node, depending on its current status.
*** Activity type: Operation Requested on a cluster host
*** Internal policies: not applicable
*** Internal timeout: 5m
** Enable {pace} at boot: Enabled when the service is disabled at boot in the corresponding host.
*** Activity type: Operation Requested on a cluster host
*** Internal policies: not applicable
*** Internal timeout: 5m
** Disable {pace} at boot: Enabled when the service is enabled at boot in the corresponding host.
*** Activity type: Operation Requested on a cluster host
*** Internal policies: not applicable
*** Internal timeout:: 5m
** Start cluster node: Enabled when the node is offline.
*** Activity type: Operation Requested on a cluster host
*** Internal policies: in a {hana} cluster, if the node is managing a secondary instance, all the nodes managing primary instances must be online
*** Internal timeout: 5m
** Stop cluster node: Enabled when the node is online.
*** Activity type: Operation Requested on a cluster host
*** Internal policies: in a {hana} cluster, if the node is managing a primary instance, all the nodes managing secondary instances must be offline
*** Internal timeout: 5m

* At resource level:
** Resource maintenance. Enabled when the corresponding node is online. It turns maintenance on or off in the resource, depending on its current status.
*** Activity type: Cluster Operation Requested
*** Internal policies: not applicable
*** Internal timeout: 5m

=== {hana} operations

For any registered {hana} database that is not part of a HANA replication system, the following operations are available at the top of the corresponding details view:

* Start database. Enabled when the database is stopped. It calls `sapcontrol` with the function `StartSystem`.
** Options:
*** Timeout: it establishes the time in minutes that {trento} waits for the database to start before initiating a rollback
** Activity type: Database Operation Requested
** Internal policies: not applicable
** Internal timeout: 12 hours

* Stop database: Enabled when the database is started. It calls `sapcontrol` with the function `StopSystem`.
** Options:
*** Timeout: it establishes the time in minutes that {trento} waits for the database to stop before initiating a rollback
** Activity type: Database Operation Requested
** Internal policies: if there is an application layer ({sap} system) on top of the database, all application server instances must be stopped
** Internal timeout: 12 hours

For any registered {hana} database that is part of a HANA replication system, the following operations are available in the corresponding sections of the details view:

* Start database. Enabled when the database is stopped. It calls `sapcontrol` with the function `StartSystem`.
** Options:
*** Timeout: it establishes the time in minutes that {trento} waits for the database to start before initiating a rollback
** Activity type: Database Operation Requested
** Internal policies:
*** If the database is managed by a {pace} cluster, the corresponding multistate resource or the cluster itself must be in maintenance mode
*** if the database is a secondary one, the corresponding primary database must be started
** Internal timeout: 12 hours

* Stop database: Enabled when the database is started. It calls `sapcontrol` with the function `StopSystem`.
** Options:
*** Timeout: it establishes the time in minutes that {trento} waits for the database to stop before initiating a rollback
** Activity type: Database Operation Requested
** Internal policies:
*** If the database is managed by a {pace} cluster, the corresponding multistate resource or the cluster itself must be in maintenance mode
*** If the database is a primary one, the corresponding secondary database must be stopped
*** If the database is a primary one and there is an application layer ({sap} system) on top of the database, all application server instances must be stopped
** Internal timeout: 12 hours

=== {sap} operations

For any registered {sap} system, the following operations are available in the corresponding details view:

* Start system. Enabled when at least one instance of the system is stopped. It calls `sapcontrol` with the function `StartSystem` and the parameter selected as Instance Type:
** Options:
*** Instance Type: the available values are:
**** All instances: select to start all the instances in the system
**** ABAP: select to start the instances with ABAP work processes
**** J2EE: select to start the instances with J2EE work processes
**** ASCS/SCS: select to start the instance with a message server and an enqueue server
**** ENQREP: select to start the instance with an enqueue replication server
*** Timeout: it establishes the time in minutes that {trento} waits for the {sap} system to start before initiating a rollback
** Activity type: {sap} System Operation Requested
** Internal policies: if any of the instances included in the Instance Type selection is managed by a cluster , the corresponding resource or the cluster itself must be in maintenance mode
** Internal timeout: 1h

* Stop system: Enabled when at least one instance of the system is started. It calls `sapcontrol` with the function `StopSystem` and the parameter selected as Instance Type:
** Options:
*** Instance Type:
**** All instances: select to stop all the instances in the system.
**** ABAP: select to stop the instances with ABAP work processes
**** J2EE: select to stop the instances with J2EE work processes
**** ASCS/SCS: select to stop the instance with a message server and an enqueue server
**** ENQREP: select to stop the instance with an enqueue replication server
*** Timeout: it establishes the time in minutes that {trento} waits for the {sap} system to stop before initiating a rollback
** Activity type: {sap} System Operation Requested
** Internal policies: if any of the instances included in the Instance Type selection is managed by a cluster, the corresponding resource or the cluster itself must be in maintenance mode.
** Internal timeout: 1h

* Start instance. Enabled when the instance is stopped. It calls `sapcontrol` with the corresponding instance number and function `Start` in the host where the instance was discovered:
** Activity type: Application Instance Operation Requested
** Internal policies:
*** If the instance is managed by a cluster, the corresponding resource or the cluster itself must be in maintenance mode
*** In the case of an application server instance, the ASCS/SCS instance and the database must be running
*** In the case of an ERS instance, the ASCS/SCS instance must be running
** Internal timeout: 5m

* Stop instance: Enabled when the instance is started. It calls `sapcontrol` with the corresponding instance number and function `Stop` in the host where the instance was discovered:
** Activity type: Application Instance Operation Requested
** Internal policies:
*** If the instance is managed by a cluster, the corresponding resource or the cluster itself must be in maintenance mode
*** In the case of an ASCS instance, the application server instances and, if it exists, the ERS instance must be stopped
** Internal timeout: 5m