include::product-attributes.adoc[]

[[sec-trento-problemanalysis]]
== Problem Analysis
:revdate: 2025-10-27


=== {trserver}

There are two tools you can use to collect information and data that can be useful when troubleshooting and analyzing issues with {trento} Server.

==== {trento} support plugin

The {trento} support plugin consists of the `trento-support.sh` script and the support plugin itself. The tool automates the collection of logs and relevant runtime information on the server side. It can be used in two different scenarios:

* A deployment on K3s  
* A systemd deployment

==== Using the {trento} support plugin with a K3s deployment

Using the plugin with a K3s deployment requires a {sles4sap} 15 SP3 or higher host with the following setup:

* Packages `jq` and `yq` are installed  
* Helm is installed  
* `kubectl` is installed and connected to the {k8s} cluster where {trserver} is running

To use the plugin, proceed as follows:

. Install the {trento} support plugin:
+
====
[source,subs="attributes"]
----
{prompt_root}zypper ref
{prompt_root}zypper install supportutils-plugin-trento
----
====
+
. Run the `trento-support.sh` script:
+
====
[source,subs="attributes"]
----
{prompt_root}trento-support.sh --output file-tgz --collect all
----
====
+
. Send the generated archive file to support for analysis.

The script accepts the following options:

* `-o`, `--output` Output type (`stdout`, `file`, `file-tgz`)
* `-c`, `--collect`  Collection options (`configuration`, `base`, `kubernetes`, `all`)
* `-r`, `--release-name` Release name to use for the chart installation. Default is `trento-server`
* `-n`, `--namespace` {k8s} namespace used when installing the chart.Default is `default`
* `--help` Shows help messages

==== Using the {trento} support plugin with a systemd deployment

To use the plugin in this scenario, proceed as follows:

. Install the {trento} support plugin:
+
====
[source,subs="attributes"]
----
{prompt_root}zypper ref
{prompt_root}zypper install supportutils-plugin-trento
----
====
+
. Execute supportconfig as described in https://documentation.suse.com/sles/html/SLES-all/cha-adm-support.html\#sec-admsupport-cli. The `supportconfig` tool will call the {trento} support plugin.
. Send the generated output to support for analysis.

=== Scenario dump script

A scenario dump is a dump of the {trento} database. It helps the {trento} team to recreate the scenario to test it.

A script is available in the {trento} upstream project. The script helps generate a scenario dump when the server is running on a {k8s} cluster. Using this script requires a host with the following setup:

* `kubectl` is installed and connected to the {k8s} cluster where {trserver} is running.

To generate the dump, proceed as follows:

. Download the latest version of the dump script:
+
====
[source,subs="attributes"]
----
{prompt_user}wget https://raw.githubusercontent.com/trento-project/web/main/hack/dump_scenario_from_k8.sh
----
====
+
. Make the script executable:
+
====
[source,subs="attributes"]
----
{prompt_user}chmod +x dump_scenario_from_k8.sh
----
====
+
. Make sure that `kubectl` is connected to the {k8s} cluster where {trserver} is running and run the script:
+
====
[source,subs="attributes"]
----
{prompt_user}./dump_scenario_from_k8.sh -n SCENARIO_NAME -p PATH
----
====
+
. Go to `PATH/scenarios/SCENARIO_NAME`, package all the generated JSON files, and send the package to support for analysis.

=== Pods descriptions and logs

In case of a deployment on K3s, the descriptions and logs of the {trserver} pods can be useful for analysis and troubleshooting purposes (in addition to the output of the trento-support.sh script and the dump scenario script). These descriptions and logs can be obtained with the `kubectl` command. For this to work, you need a host with `kubectl` is installed and connected to the K3s cluster running {trserver}.

. List the pods running in {k8s} cluster and their statuses. Run the command below to view {trserver} pods:
+
====
[source,subs="attributes"]
----
{prompt_user}kubectl get pods
  
NAME                                               READY   STATUS    RESTARTS   AGE
trento-server-postgresql-0                         1/1     Running   0          87m
trento-server-prometheus-server-7b5c9474bc-wmv8s   2/2     Running   0          87m
trento-server-rabbitmq-0                           1/1     Running   0          87m
trento-server-wanda-67ffbb79dc-7t6xw               1/1     Running   0          87m
trento-server-web-7df8f65794-vdbhs                 1/1     Running   0          87m
----
====
+
. Retrieve the description of a pod as follows:
+
====
[source,subs="attributes"]
----
{prompt_user}kubectl describe pod POD_NAME
----
====
+
. Retrieve the log of a pod as follows:
+
====
[source,subs="attributes"]
----
{prompt_user}kubectl logs POD_NAME
----
====
+
. Monitor the log of a pod as follows:
+
====
[source,subs="attributes"]
----
{prompt_user}kubectl logs POD_NAME --follow
----
====