= Installation of Trento

////
We use the systemd-install.xml as a reference to keep the content aligned.
Source https://github.com/SUSE/doc-unversioned/blob/main/trento/xml/systemd-install.xml
Changed title from systemd deployment to Installation of Trento
Added " based on RPM packages or containerized  deployment" as this document is combined.
////
A systemd installation of Trento Server, based on RPM packages or containerized deployment, can be
done manually. The latest available version of SUSE Linux Enterprise
Server for SAP Applications is used as the base operating system, which
is https://www.suse.com/download/sles/[SLE 15 SP5] at the time of
writing. For installations on Service Packs other than SP5, update the
repository address as indicated in the respective notes provided
throughout this guide.

*Supported Service Packs*:

* SP3
* SP4
* SP5

== List of dependencies

* https://www.postgresql.org/[PostgreSQL]
* https://rabbitmq.com/[RabbitMQ]
* https://nginx.org/en/[NGINX]
// Added docker reference as we combine systemd-install.xml with container-install.xml
* https://www.docker.com/[Docker] (optional)
* https://prometheus.io/[Prometheus] (optional)

== Install Trento dependencies

=== Install Prometheus (Optional)

https://prometheus.io/[Prometheus] is not required to run Trento, but it
is recommended, as it allows Trento to display charts for each host with
useful information about the CPU load, memory, and other important
metrics.

[NOTE]
====
If you choose not to install Prometheus, or you choose to use an
existing installation, make sure that `+CHARTS_ENABLED+` is set to
`+false+` in the Trento web RPM configuration file stored at
`+/etc/trento/trento-web+`, or when it is provided to the Trento web
container.
====

==== Option 1: Use existing installation

Minimal required Prometheus version is *2.28.0*.

If you have a https://prometheus.io/docs/prometheus/latest/installation/[existing
Prometheus server], ensure to set the PROMETHEUS_URL environment
variable to your Prometheus server's URL as part of the Docker command
when creating the `+trento-web+` container or configuring the RPM
packages. Use `+Option 2: Install Prometheus using the PackageHub repository+` as a reference to
adjust the Prometheus configuration.

==== Option 2: Install Prometheus using the *unsupported* PackageHub repository

https://packagehub.suse.com/[PackageHub] packages are tested by SUSE,
but they do not come with the same level of support as the core SLES
packages. Users should assess the suitability of these packages based on
their own risk tolerance and support needs.

. Enable PackageHub repository:
+
[source,bash]
----
SUSEConnect --product PackageHub/15.5/x86_64
----
+
[NOTE]
====
SLE15 SP3 requires a provided Prometheus server. The version available
through `+SUSEConnect --product PackageHub/15.3/x86_64+` is outdated and
is not compatible with Trento's Prometheus configuration. Refer to
link:#option-1-use-existing-installation[Option 1: Use existing
installation] for SLE 15 SP3.
====
+
[NOTE]
====
For SLE15 SP4 change the repository to
`+SUSEConnect --product PackageHub/15.4/x86_64+`
====
. Add the Prometheus user/group:
+
[source,bash]
----
groupadd --system prometheus
useradd -s /sbin/nologin --system -g prometheus prometheus
----
. Install Prometheus using Zypper:
+
[source,bash]
----
zypper in golang-github-prometheus-prometheus
----
+
[NOTE]
====
In case the missing dependency cannot be satisfied, we have already
added the Prometheus user/group. This makes it safe to proceed with the
installation by choosing *Solution 2: break
golang-github-prometheus-prometheus'
====
. Change Prometheus configuration by replacing the configuration at
`+/etc/prometheus/prometheus.yml+` with:
+
[source,yaml]
----
global:
  scrape_interval: 30s
  evaluation_interval: 10s

scrape_configs:
  - job_name: "http_sd_hosts"
    honor_timestamps: true
    scrape_interval: 30s
    scrape_timeout: 30s
    scheme: http
    follow_redirects: true
    http_sd_configs:
      - follow_redirects: true
        refresh_interval: 1m
        url: http://localhost:4000/api/prometheus/targets
----
+
[NOTE]
====
*localhost:4000* in *url:http://localhost:4000/api/prometheus/targets*
refers to the location where Trento web service is running.
====
. Enable and start the Prometheus service:
+
[source,bash]
----
systemctl enable --now prometheus
----
. If firewalld is running, allow Prometheus to be accessible and add an
exception to firewalld:
+
[source,bash]
----
firewall-cmd --zone=public --add-port=9090/tcp --permanent
firewall-cmd --reload
----

=== Install PostgreSQL

The current instructions are tested with the following PostgreSQL
version:

* *13.9 for SP3*
* *14.10 for SP4*
* *15.5 for SP5*

Using a different version of PostgreSQL may require different steps or
configurations, especially when changing the major number. For more
details, refer to the official
https://www.postgresql.org/docs/[PostgreSQL documentation].

. Install PostgreSQL server:
+
[source,bash]
----
zypper in postgresql-server
----
. Enable and start PostgreSQL server:
+
[source,bash]
----
systemctl enable --now postgresql
----

==== Configure PostgreSQL

. Start `+psql+` with the `+postgres+` user to open a connection to the
database:
+
[source,bash]
----
su - postgres
psql
----
. Initialize the databases in the `+psql+` console:
+
[source,sql]
----
CREATE DATABASE wanda;
CREATE DATABASE trento;
CREATE DATABASE trento_event_store;
----
. Create the users:
+
[source,sql]
----
CREATE USER wanda_user WITH PASSWORD 'wanda_password';
CREATE USER trento_user WITH PASSWORD 'web_password';
----
. Grant required privileges to the users and close the connection:
+
[source,sql]
----
\c wanda
GRANT ALL ON SCHEMA public TO wanda_user;
\c trento
GRANT ALL ON SCHEMA public TO trento_user;
\c trento_event_store;
GRANT ALL ON SCHEMA public TO trento_user;
\q
----
+
You can exit from the `+psql+` console and `+postgres+` user.
. Allow the PostgreSQL database to receive connections to the respective
databases and users. To do this, add the following to
`+/var/lib/pgsql/data/pg_hba.conf+`:
+
[source,bash]
----
host   wanda                      wanda_user    0.0.0.0/0   md5
host   trento,trento_event_store  trento_user   0.0.0.0/0   md5
----
+
[NOTE]
====
The `+pg_hba.conf+` file works sequentially. This means that the rules
on the top have preference over the ones below. The example above shows
a permissive address range. So for this to work, the entires must be
written at the top of the `+host+` entries. For further information,
refer to the https://www.postgresql.org/docs/current/auth-pg-hba-conf.html[pg_hba.conf] documentation.
====
. Allow PostgreSQL to bind on all network interfaces in
`+/var/lib/pgsql/data/postgresql.conf+` by changing the following line:
+
[source,bash]
----
listen_addresses = '*'
----
. Restart PostgreSQL to apply the changes:
+
[source,bash]
----
systemctl restart postgresql
----

=== Install RabbitMQ

. Install RabbitMQ server:
+
[source,bash]
----
zypper install rabbitmq-server
----
. Allow connections from external hosts by modifying
`+/etc/rabbitmq/rabbitmq.conf+`, so the Trento-agent can reach RabbitMQ:
+
[source,ini files]
----
listeners.tcp.default = 5672
----
. If firewalld is running, add a rule to firewalld:
+
[source,bash]
----
firewall-cmd --zone=public --add-port=5672/tcp --permanent;
firewall-cmd --reload
----
. Enable the RabbitMQ service:
+
[source,bash]
----
systemctl enable --now rabbitmq-server
----

==== Configure RabbitMQ

To configure RabbitMQ for a production system, follow the official
suggestions in the
https://www.rabbitmq.com/production-checklist.html[RabbitMQ guide].

. Create a new RabbitMQ user:
+
[source,bash]
----
rabbitmqctl add_user trento_user trento_user_password
----
. Create a virtual host:
+
[source,bash]
----
rabbitmqctl add_vhost vhost
----
. Set permissions for the user on the virtual host:
+
[source,bash]
----
rabbitmqctl set_permissions -p vhost trento_user ".*" ".*" ".*"
----

// Added a link, which differs from source
[[systemd-deployment]]
=== Install Trento using RPM packages

The `+trento-web+` and `+trento-wanda+` packages come in the supported
SLES4SAP distributions by default.

Install Trento web and wanda:

[source,bash]
----
zypper install trento-web trento-wanda
----

==== Create the configuration files

Both services depend on respective configuration files. They must be
placed in `+/etc/trento/trento-web+` and `+/etc/trento/trento-wanda+`
respectively, and examples of how to modify them are available in
`+/etc/trento/trento-web.example+` and
`+/etc/trento/trento-wanda.example+`.

*Important: The content of `+SECRET_KEY_BASE+` and
`+ACCESS_TOKEN_ENC_SECRET+` in both `+trento-web+` and `+trento-wanda+`
must be the same.*

[NOTE]
====
You can create the content of the secret variables like
`+SECRET_KEY_BASE+`, `+ACCESS_TOKEN_ENC_SECRET+` and
`+REFRESH_TOKEN_ENC_SECRET+` with `+openssl+` running
`+openssl rand -out /dev/stdout 48 | base64+`
====

[NOTE]
====
Depending on how you intend to connect to the console, a working
hostname, FQDN, or an IP is required in `+TRENTO_WEB_ORIGIN+` for HTTPS.
Otherwise websockets fail to connect, causing no real-time updates in
the UI.
====

==== trento-web configuration

....
# /etc/trento/trento-web
AMQP_URL=amqp://trento_user:trento_user_password@localhost:5672/vhost
DATABASE_URL=ecto://trento_user:web_password@localhost/trento
EVENTSTORE_URL=ecto://trento_user:web_password@localhost/trento_event_store
ENABLE_ALERTING=false
CHARTS_ENABLED=true
PROMETHEUS_URL=http://localhost:9090
ADMIN_USER=admin
ADMIN_PASSWORD=test1234
ENABLE_API_KEY=true
PORT=4000
TRENTO_WEB_ORIGIN=trento.example.com
SECRET_KEY_BASE=some-secret
ACCESS_TOKEN_ENC_SECRET=some-secret
REFRESH_TOKEN_ENC_SECRET=some-secret
....

[NOTE]
====
*Note:* Add `+CHARTS_ENABLED=false+` in Trento web configuration file if
Prometheus is not installed or you do not want to use Trento's charts
functionality.
====

The https://github.com/trento-project/web/blob/main/guides/alerting/alerting.md[alerting system to receive email notifications] can be enabled by setting `+ENABLE_ALERTING+` to `+true+` and adding the following entries:

....
# /etc/trento/trento-web
ENABLE_ALERTING=true
ALERT_SENDER=<<SENDER_EMAIL_ADDRESS>>
ALERT_RECIPIENT=<<RECIPIENT_EMAIL_ADDRESS>>
SMTP_SERVER=<<SMTP_SERVER_ADDRESS>>
SMTP_PORT=<<SMTP_PORT>>
SMTP_USER=<<SMTP_USER>>
SMTP_PASSWORD=<<SMTP_PASSWORD>>
....

==== trento-wanda configuration

....
# /etc/trento/trento-wanda
CORS_ORIGIN=http://localhost
AMQP_URL=amqp://trento_user:trento_user_password@localhost:5672/vhost
DATABASE_URL=ecto://wanda_user:wanda_password@localhost/wanda
PORT=4001
SECRET_KEY_BASE=some-secret
ACCESS_TOKEN_ENC_SECRET=some-secret
....

==== Start the services

Enable and start the services:

[source,bash]
----
systemctl enable --now trento-web trento-wanda
----

==== Monitor the services

Use `+journalctl+` to check if the services are up and running
correctly. For example:

[source,bash]
----
journalctl -fu trento-web
----

[[validate-the-health-status-of-trento-web-and-wanda]]
=== Check the health status of trento web and wanda

You can check if Trento web and wanda services function correctly by
accessing accessing the `+healthz+` and `+readyz+` API.

. Check Trento web health status using `+curl+`:
+
[source,bash]
----
curl http://localhost:4000/api/readyz
----
+
[source,bash]
----
curl http://localhost:4000/api/healthz
----
. Check Trento wanda health status using `+curl+`:
+
[source,bash]
----
curl http://localhost:4001/api/readyz
----
+
[source,bash]
----
curl http://localhost:4001/api/healthz
----

If Trento web and wanda are ready, and the database connection is set up
correctly, the output should be as follows:

----
{"ready":true}{"database":"pass"}
----

////
Inserted container-install.xml article into systemd-install.xml
Source: https://github.com/SUSE/doc-unversioned/blob/main/trento/xml/container-install.xml
////
== Containerized deployment

A containerized deployment of Trento Server is identical to a systemd
deployment. However, the web and check engine components are deployed as Docker containers.

Follow the steps in link:#systemd-deployment[systemd deployment section], but skip the *Install Trento using RPM packages* step and follow the procedures in
link:#install-trento-using-docker[Install Trento using Docker].

=== Install Trento using Docker
==== Install Docker container runtime

. Enable the containers module:
+
[source,bash]
----
SUSEConnect --product sle-module-containers/15.5/x86_64
----
+
[NOTE]
====
To use a different Service Pack than SP5, you have to choose the
appropriate repository. For example,
`+SUSEConnect --product sle-module-containers/15.3/x86_64+` for SLE15
SP3, `+SUSEConnect --product sle-module-containers/15.4/x86_64+` for
SLE15 SP4.
====
. Install Docker:
+
[source,bash]
----
zypper install docker
----
. Enable and start Docker:
+
[source,bash]
----
systemctl enable --now docker
----

==== Create a dedicated Docker network for Trento

. Create the Trento Docker network:
+
[source,bash]
----
docker network create trento-net
----
+
[NOTE]
====
When creating the `+trento-net+` network, Docker assigns a default
subnet to it: `+172.17.0.0/16+`. Ensure that this subnet is allowed by
the rules specified in your PostgreSQL configuration. For more
information, refer to the upstream
https://www.postgresql.org/docs/current/auth-pg-hba-conf.html[`+pg_hba.conf+`]
documentation.
====
. Verify the subnet of `+trento-net+`:
+
[source,bash]
----
docker network inspect trento-net --format '{{range .IPAM.Config}}{{.Subnet}}{{end}}'
----
+
Expected output is as follows:
+
[source,bash]
----
172.17.0.0/16
----

==== Install Trento on Docker

. Create secret environment variables:
+
[NOTE]
====
Consider using an environment variable file (see
https://docs.docker.com/engine/reference/commandline/run/#env[official
Docker documentation]). Adjust the docker command below for use with the
env file. In any case, make sure you keep a copy of the generated keys
in a safe location, in case you need to reuse them in the future.
====
+
[source,bash]
----
WANDA_SECRET_KEY_BASE=$(openssl rand -out /dev/stdout 48 | base64)
TRENTO_SECRET_KEY_BASE=$(openssl rand -out /dev/stdout 48 | base64)
ACCESS_TOKEN_ENC_SECRET=$(openssl rand -out /dev/stdout 48 | base64)
REFRESH_TOKEN_ENC_SECRET=$(openssl rand -out /dev/stdout 48 | base64)
----
. Install the checks on the system in a shared volume:
+
[source,bash]
----
docker volume create trento-checks \
  && docker run \
  -v trento-checks:/usr/share/trento/checks \
  registry.suse.com/trento/trento-checks:latest
----
. Deploy trento-wanda:
+
[source,bash]
----
docker run -d --name wanda \
    -p 4001:4000 \
    --network trento-net \
    --add-host "host.docker.internal:host-gateway" \
    -v trento-checks:/usr/share/trento/checks:ro \
    -e CORS_ORIGIN=localhost \
    -e SECRET_KEY_BASE=$WANDA_SECRET_KEY_BASE \
    -e ACCESS_TOKEN_ENC_SECRET=$ACCESS_TOKEN_ENC_SECRET \
    -e AMQP_URL=amqp://trento_user:trento_user_password@host.docker.internal/vhost \
    -e DATABASE_URL=ecto://wanda_user:wanda_password@host.docker.internal/wanda \
    --restart always \
    --entrypoint /bin/sh \
    registry.suse.com/trento/trento-wanda:latest \
    -c "/app/bin/wanda eval 'Wanda.Release.init()' && /app/bin/wanda start"
----
. Deploy trento-web.
+
Make sure to change the `+ADMIN_USER+` and `+ADMIN_PASSWORD+`, these are
the credentials that are required to login to the trento-web UI.
Depending on how you intend to connect to the console, a working
hostname, FQDN, or an IP is required in `+TRENTO_WEB_ORIGIN+` for HTTPS.
Otherwise websockets fail to connect, causing no real-time updates on
the UI.
+
[NOTE]
====
Add `+CHARTS_ENABLED=false+` if Prometheus is not installed, or you do
not want to use Trento's charts functionality.
====
+
[source,bash]
----
docker run -d \
-p 4000:4000 \
--name trento-web \
--network trento-net \
--add-host "host.docker.internal:host-gateway" \
-e AMQP_URL=amqp://trento_user:trento_user_password@host.docker.internal/vhost \
-e ENABLE_ALERTING=false \
-e DATABASE_URL=ecto://trento_user:web_password@host.docker.internal/trento \
-e EVENTSTORE_URL=ecto://trento_user:web_password@host.docker.internal/trento_event_store \
-e PROMETHEUS_URL='http://host.docker.internal:9090' \
-e SECRET_KEY_BASE=$TRENTO_SECRET_KEY_BASE \
-e ACCESS_TOKEN_ENC_SECRET=$ACCESS_TOKEN_ENC_SECRET \
-e REFRESH_TOKEN_ENC_SECRET=$REFRESH_TOKEN_ENC_SECRET \
-e ADMIN_USER='admin' \
-e ADMIN_PASSWORD='test1234' \
-e ENABLE_API_KEY='true' \
-e TRENTO_WEB_ORIGIN='trento.example.com' \
--restart always \
--entrypoint /bin/sh \
registry.suse.com/trento/trento-web:latest \
-c "/app/bin/trento eval 'Trento.Release.init()' && /app/bin/trento start"
----
+
Email alerting are disabled by default, as described in
https://github.com/trento-project/web/blob/main/guides/alerting/alerting.md#enabling-alerting[enabling
alerting] guide. Enable alerting by setting `+ENABLE_ALERTING+` env to
`+true+`. Additional required variables are:
`+[ALERT_SENDER,ALERT_RECIPIENT,SMTP_SERVER,SMTP_PORT,SMTP_USER,SMTP_PASSWORD]+`
All other settings should remain at their default.
+
Example:
+
[source,bash]
----
docker run -d \

...[other settings]...

-e ENABLE_ALERTING=true \
-e ALERT_SENDER=<<SENDER_EMAIL_ADDRESS>> \
-e ALERT_RECIPIENT=<<RECIPIENT_EMAIL_ADDRESS>> \
-e SMTP_SERVER=<<SMTP_SERVER_ADDRESS>> \
-e SMTP_PORT=<<SMTP_PORT>> \
-e SMTP_USER=<<SMTP_USER>> \
-e SMTP_PASSWORD=<<SMTP_PASSWORD>> \

...[other settings]...
----
. Check that everything is running as expected:
+
[source,bash]
----
docker ps
----
+
Expected output:
+
[source,bash]
----
CONTAINER ID   IMAGE                                         COMMAND                  CREATED          STATUS          PORTS                                       NAMES
8b44333aec39   registry.suse.com/trento/trento-web:2.2.0    "/bin/sh -c '/app/bi…"   6 seconds ago    Up 5 seconds    0.0.0.0:4000->4000/tcp, :::4000->4000/tcp   trento-web
e859c07888ca   registry.suse.com/trento/trento-wanda:1.2.0   "/bin/sh -c '/app/bi…"   18 seconds ago   Up 16 seconds   0.0.0.0:4001->4000/tcp, :::4001->4000/tcp   wanda
----
+
Both containers must run and listen on the specified ports

////
End of the container-install.xml article
Source: https://github.com/SUSE/doc-unversioned/blob/main/trento/xml/container-install.xml
////

////
Inserted sso-integration.xml article into systemd-install.xml
Source: https://github.com/SUSE/doc-unversioned/blob/main/trento/xml/sso-integration.xml
////

[[integrating-single-sign-on]]
== Single Sign-On integration

Trento can be integrated for Single Sign-On with a third-party identity
provider (IDP).

[NOTE]
====
Trento cannot start with multiple SSO options together, so only one can
be chosen.
====

The following protocols are supported:

* OpenID Connect (OIDC)
* Open Authorization 2.0 (OAuth 2)
* Security Assertion Markup Language (SAML)

=== User Roles and Authentication

User authentication is entirely managed by the IDP, which is responsible
for maintaining user accounts. A user, who does not exist on the IDP, is
unable to access the Trento web console.

During the installation process, a default admin user is defined using
the `+ADMIN_USER+` variable, which defaults to `+admin+`. If the
authenticated user’s IDP username matches this admin user's username,
that user is automatically granted `+all:all+` permissions within
Trento.

User permissions are entirely managed by Trento, they are not imported
from the IDP. The abilities must be granted by some user with
`+all:all+` or `+all:users+` abilities (admin user initially). This
means that only basic user information is retrieved from the external
IDP.

=== Using OpenID Connect

Trento integrates with an IDP that uses the OIDC protocol to
authenticate users accessing the Trento web console.

By default, OIDC is disabled. You can enable OIDC when using RPM
packages or using Docker images.

==== Enabling OpenID Connect when using kubernetes deployment

To enable OIDC when using kubernetes deployment with helm, proceed as
follows:

[arabic]
. Add the following variables to the previously documented helm
installation command:
+
....
HELM_EXPERIMENTAL_OCI=1 helm ... \
   --set trento-web.oidc.enabled=true \
   --set trento-web.oidc.clientId=<OIDC_CLIENT_ID> \
   --set trento-web.oidc.clientSecret=<OIDC_CLIENT_SECRET> \
   --set trento-web.oidc.baseUrl=<OIDC_BASE_URL>
....

==== Enabling OpenID Connect when using RPM packages

To enable OIDC when using RPM packages, proceed as follows:

[arabic]
. Open the file `+/etc/trento/trento-web+`.
. Add the following environment variables to this file. Required
variables are:
+
....
ENABLE_OIDC=true
OIDC_CLIENT_ID=<OIDC_CLIENT_ID>
OIDC_CLIENT_SECRET=<OIDC_CLIENT_SECRET>
OIDC_BASE_URL=<OIDC_BASE_URL>
....
. Optionally, add the OIDC callback URL to the configuration. This can
be useful if for some reason the default callback URL cannot be used,
for example, if `+http+` is used instead of `+https+`. Use the next
variable for that:
+
....
OIDC_CALLBACK_URL=<OIDC_CALLBACK_URL>
....
. Restart the application.

==== Enabling OpenID Connect when using Docker images

To enable OIDC when using Docker images, proceed as follows:

[arabic]
. If `+trento-web+` container is already running stop and delete the
container before continuing. For that run:
+
[source,bash]
----
docker stop trento-web
docker rm trento-web
----
. Provide the following environment variables to the Docker container
via the `+-e+` option:
+
[source,bash]
----
docker run -d \
-p 4000:4000 \
--name trento-web \
--network trento-net \
--add-host "host.docker.internal:host-gateway" \

...[other settings]...

# Required:
-e ENABLE_OIDC=true \
-e OIDC_CLIENT_ID=<OIDC_CLIENT_ID> \
-e OIDC_CLIENT_SECRET=<OIDC_CLIENT_SECRET> \
-e OIDC_BASE_URL=<OIDC_BASE_URL> \

# Optional:
-e OIDC_CALLBACK_URL=<OIDC_CALLBACK_URL> \

...[other settings]...
----

==== Available variables for OpenID Connect

OIDC_CLIENT_ID::
  OIDC client id
OIDC_CLIENT_SECRET::
  OIDC client secret
OIDC_BASE_URL::
  OIDC base url
OIDC_CALLBACK_URL::
  OIDC callback url where the IDP is redirecting once the authentication
  is completed (default value:
  https://#{TRENTO_WEB_ORIGIN}/auth/oidc_callback[https://#\{TRENTO_WEB_ORIGIN}/auth/oidc_callback])

[[using-oauth-20]]
=== Using OAuth 2.0

Trento integrates with an IDP that uses the OAuth 2 protocol to
authenticate users accessing the Trento web console.

By default, OAuth 2.0 is disabled. You can enable OIDC when using RPM
packages or using Docker images.

[[enabling-oauth-20-when-using-kubernetes-deployment]]
==== Enabling OAuth 2.0 when using kubernetes deployment

To enable OAuth 2.0 when using kubernetes deployment with helm, proceed
as follows:

[arabic]
. Add the following variables to the previously documented helm
installation command:
+
....
HELM_EXPERIMENTAL_OCI=1 helm ... \
   --set trento-web.oauth2.enabled=true \
   --set trento-web.oauth2.clientId=<OAUTH2_CLIENT_ID> \
   --set trento-web.oauth2.clientSecret=<OAUTH2_CLIENT_SECRET> \
   --set trento-web.oauth2.baseUrl=<OAUTH2_BASE_URL> \
   --set trento-web.oauth2.authorizeUrl=<OAUTH2_AUTHORIZE_URL> \
   --set trento-web.oauth2.tokenUrl=<OAUTH2_TOKEN_URL> \
   --set trento-web.oauth2.userUrl=<OAUTH2_USER_URL>
....
+
Additionally, the following optional values are available:
+
....
HELM_EXPERIMENTAL_OCI=1 helm ... \
   --set trento-web.oauth2.scopes=<OAUTH2_SCOPES>
....

[[enabling-oauth-20-when-using-rpm-packages]]
==== Enabling OAuth 2.0 when using RPM packages

To enable OAuth 2.0 when using RPM packages, proceed as follows:

[arabic]
. Open the file `+/etc/trento/trento-web+`.
. Add the following environment variables to this file. Required
variables are:
+
....
# Required:
ENABLE_OAUTH2=true
OAUTH2_CLIENT_ID=<OAUTH2_CLIENT_ID>
OAUTH2_CLIENT_SECRET=<OAUTH2_CLIENT_SECRET>
OAUTH2_BASE_URL=<OAUTH2_BASE_URL>
OAUTH2_AUTHORIZE_URL=<OAUTH2_AUTHORIZE_URL>
OAUTH2_TOKEN_URL=<OAUTH2_TOKEN_URL>
OAUTH2_USER_URL=<OAUTH2_USER_URL>

# Optional:
OAUTH2_SCOPES=<OAUTH2_SCOPES>
OAUTH2_CALLBACK_URL=<OAUTH2_CALLBACK_URL>
....
. Restart the application.

[[enabling-oauth-20-when-using-docker-images]]
==== Enabling OAuth 2.0 when using Docker images

To enable OAuth 2.0 when using Docker images, proceed as follows:

[arabic]
. If `+trento-web+` container is already running stop and delete the
container before continuing. For that run:
+
[source,bash]
----
docker stop trento-web
docker rm trento-web
----
. Use the following environment variables to the Docker container via
the `+-e+` option:
+
[source,bash]
----
docker run -d \
-p 4000:4000 \
--name trento-web \
--network trento-net \
--add-host "host.docker.internal:host-gateway" \

...[other settings]...

-e ENABLE_OAUTH2=true \
-e OAUTH2_CLIENT_ID=<OAUTH2_CLIENT_ID> \
-e OAUTH2_CLIENT_SECRET=<OAUTH2_CLIENT_SECRET> \
-e OAUTH2_BASE_URL=<OAUTH2_BASE_URL> \
-e OAUTH2_AUTHORIZE_URL=<OAUTH2_AUTHORIZE_URL> \
-e OAUTH2_TOKEN_URL=<OAUTH2_TOKEN_URL> \
-e OAUTH2_USER_URL=<OAUTH2_USER_URL> \

# Optional:
-e OAUTH2_SCOPES=<OAUTH2_SCOPES> \
-e OAUTH2_CALLBACK_URL=<OAUTH2_CALLBACK_URL> \

...[other settings]...
----

[[available-variables-for-oauth-20]]
==== Available variables for OAuth 2.0

OAUTH2_CLIENT_ID::
  OAUTH2 client id
OAUTH2_CLIENT_SECRET::
  OAUTH2 client secret
OAUTH2_BASE_URL::
  OAUTH2 base url
OAUTH2_AUTHORIZE_URL::
  OAUTH2 authorization url
OAUTH2_TOKEN_URL::
  OAUTH2 token url
OAUTH2_USER_URL::
  OAUTH2 token url
OAUTH2_SCOPES::
  OAUTH2 scopes, used to define the user values sent to the SP. It must
  be adjusted depending on IDP provider requirements (default value:
  `+profile email+`)
OAUTH2_CALLBACK_URL::
  OAUTH2 callback url where the IDP is redirecting once the
  authentication is completed (default value:
  `+https://#{TRENTO_WEB_ORIGIN}/auth/oauth2_callback+`)

=== Using SAML

Trento integrates with an IDP that uses the SAML protocol to
authenticate users accessing the Trento web console. Trento will behave
as a Service Provider (SP) in this case.

Commonly, SAML protocol messages are signed with SSL. This is optional
using Trento, and the signing is not required (even though it is
recommended). If the IDP signs the messages, and expect signed messages
back, certificates used by the SP (Trento in this case) must be provided
to the IDP, the public certificate file in this case.

To use an existing SAML IDP, follow the next instrunctions to met the
specific requirements. You need:

[arabic]
. Obtain metadata content from the IDP
. Start Trento to generate the certificates and get them (SAML must be
enabled for this)
. Provide the generated certificate to the IDP
. Configure SAML IDP and user profiles

See the following subsections for details.

==== Obtaining metadata content from the IDP

The `+metadata.xml+` file defines the agreement between SP and IDP
during SAML communications. It is used to identify the SAML client as
well. The content of this file must be provided to Trento. Options
`+SAML_METADATA_URL+` and `+SAML_METADATA_CONTENT+` are available for
that.

If the `+SAML_METADATA_CONTENT+` option is being used, the content of
this variable must be updated with the IDP metadata as single line
string. On the other hand, if `+SAML_METADATA_URL+` is used, the new
metadata is automatically fetched when Trento starts. If neither of
these steps are completed, communication will fail because the message
signatures will not be recognized.

If the used IDP has the endpoint to provide the `+metadata.xml+` file
content, prefer the variable `+SAML_METADATA_URL+`. Trento will
automatically fetch metadata when started.

==== Getting certificates from Trento

Trento provides a certificates set created during the installation.
Regardless of the installation mode, when Trento is installed the first
time and SAML is enabled the certificates are created and the public
certificate file content is available in the
https://#{TRENTO_WEB_ORIGIN}/api/public_keys[https://#\{TRENTO_WEB_ORIGIN}/api/public_keys]
route.

Use the following command to get the certificate content:

[source,bash]
----
curl https://#{TRENTO_WEB_ORIGIN}/api/public_keys
----

Copy the content of the certificate from there and provide it to the
IDP. This way, the IDP will sign its messages and verify the messages
received from Trento.

[NOTE]
====
To get the certificate using this route Trento must be configured to
start with SAML enabled.
====

==== Configuring SAML IDP setup

Configure the existing IDP with the next minimum options to be able to
connect with Trento as a Service Provider (SP).

===== Providing certificates

As commented previously, a set of certificates is needed to enable
signed communication. Provide the certificate generated by Trento to the
IDP (each IDP has a different way to do this). Make sure that the
configured certificate is used for signing and encrypting messages.

===== Configuring SAML user profile

Users provided by the SAML installation must have some few mandatory
attributes to login in Trento. The required attributes are: username,
email, first name and last name. All of them are mandatory, even though
their field names are configurable.

By default, Trento expects the `+username+`, `+email+`, `+firstName+`
and `+lastName+` attribute names. All these 4 attribute names are
configurable using the next environment variables, following the same
order: `+SAML_USERNAME_ATTR_NAME+`, `+SAML_EMAIL_ATTR_NAME+`,
`+SAML_FIRSTNAME_ATTR_NAME+` and `+SAML_LASTNAME_ATTR_NAME+`.

Both IDP and Trento must know how these 4 fields are mapped. To do this,
follow the next instructions:

[arabic]
. Add the attributes if they don't exist in the IDP user profile. If
they already exist, don't change the attributes and keep their original
values.
. Configure Trento to use the IDP attribute field names. To do this, set
the `+SAML_USERNAME_ATTR_NAME+`, `+SAML_EMAIL_ATTR_NAME+`,
`+SAML_FIRSTNAME_ATTR_NAME+` and `+SAML_LASTNAME_ATTR_NAME+` environment
values with the values configured in the IDP. For example, if the IDP
user profile username is defined as `+attr:username+` use
`+SAML_USERNAME_ATTR_NAME=attr:username+`.

===== Checking SAML redirect URI

After a successful login, the IDP redirects the user's session back to
Trento and redirected at https://trento.example.com/sso/sp/consume/saml.
To ensure seamless SSO, this URI must be configured as valid within the
IDP.

==== Enabling SAML when using kubernetes deployment

To enable SAML when using kubernetes deployment with helm, proceed as
follows:

[arabic]
. Add the following variables to the previously documented helm
installation command:
+
....
HELM_EXPERIMENTAL_OCI=1 helm ... \
   --set trento-web.saml.enabled=true \
   --set trento-web.saml.idpId=<SAML_IDP_ID> \
   --set trento-web.saml.spId=<SAML_SP_ID> \
   --set trento-web.saml.metadataUrl=<SAML_METADATA_URL>
....
+
To use the `+SAML_METADATA_CONTENT+` option rather than
`+SAML_METADATA_URL+` use:
+
....
HELM_EXPERIMENTAL_OCI=1 helm ... \
   --set trento-web.saml.enabled=true \
   --set trento-web.saml.idpId=<SAML_IDP_ID> \
   --set trento-web.saml.spId=<SAML_SP_ID> \
   --set trento-web.saml.metadataContent=<SAML_METADATA_CONTENT>
....
+
Additionally, the following optional values are available:
+
....
HELM_EXPERIMENTAL_OCI=1 helm ... \
   --set trento-web.saml.idpNameIdFormat=<SAML_IDP_NAMEID_FORMAT> \
   --set trento-web.saml.spDir=<SAML_SP_DIR> \
   --set trento-web.saml.spEntityId=<SAML_SP_ENTITY_ID> \
   --set trento-web.saml.spContactName=<SAML_SP_CONTACT_NAME> \
   --set trento-web.saml.spContactEmail=<SAML_SP_CONTACT_EMAIL> \
   --set trento-web.saml.spOrgName=<SAML_SP_ORG_NAME> \
   --set trento-web.saml.spOrgDisplayName=<SAML_SP_ORG_DISPLAYNAME> \
   --set trento-web.saml.spOrgUrl=<SAML_SP_ORG_URL> \
   --set trento-web.saml.usernameAttrName=<SAML_USERNAME_ATTR_NAME> \
   --set trento-web.saml.emailAttrName=<SAML_EMAIL_ATTR_NAME> \
   --set trento-web.saml.firstNameAttrName=<SAML_FIRSTNAME_ATTR_NAME> \
   --set trento-web.saml.lastNameAttrName=<SAML_LASTNAME_ATTR_NAME> \
   --set trento-web.saml.signRequests=<SAML_SIGN_REQUESTS> \
   --set trento-web.saml.signMetadata=<SAML_SIGN_METADATA> \
   --set trento-web.saml.signedAssertion=<SAML_SIGNED_ASSERTION> \
   --set trento-web.saml.signedEnvelopes=<SAML_SIGNED_ENVELOPES>
....

==== Enabling SAML when using RPM packages

To enable SAML when using RPM packages, proceed as follows:

[arabic]
. Open the file `+/etc/trento/trento-web+`.
. Add the following environment variables to this file. Required
variables are:
+
....
# Required:
ENABLE_SAML=true
SAML_IDP_ID=<SAML_IDP_ID>
SAML_SP_ID=<SAML_SP_ID>
# Only SAML_METADATA_URL or SAML_METADATA_CONTENT must by provided
SAML_METADATA_URL=<SAML_METADATA_URL>
SAML_METADATA_CONTENT=<SAML_METADATA_CONTENT>

# Optional:
SAML_IDP_NAMEID_FORMAT=<SAML_IDP_NAMEID_FORMAT>
SAML_SP_DIR=<SAML_SP_DIR>
SAML_SP_ENTITY_ID=<SAML_SP_ENTITY_ID>
SAML_SP_CONTACT_NAME=<SAML_SP_CONTACT_NAME>
SAML_SP_CONTACT_EMAIL=<SAML_SP_CONTACT_EMAIL>
SAML_SP_ORG_NAME=<SAML_SP_ORG_NAME>
SAML_SP_ORG_DISPLAYNAME=<SAML_SP_ORG_DISPLAYNAME>
SAML_SP_ORG_URL=<SAML_SP_ORG_URL>
SAML_USERNAME_ATTR_NAME=<SAML_USERNAME_ATTR_NAME>
SAML_EMAIL_ATTR_NAME=<SAML_EMAIL_ATTR_NAME>
SAML_FIRSTNAME_ATTR_NAME=<SAML_FIRSTNAME_ATTR_NAME>
SAML_LASTNAME_ATTR_NAME=<SAML_LASTNAME_ATTR_NAME>
SAML_SIGN_REQUESTS=<SAML_SIGN_REQUESTS>
SAML_SIGN_METADATA=<SAML_SIGN_METADATA>
SAML_SIGNED_ASSERTION=<SAML_SIGNED_ASSERTION>
SAML_SIGNED_ENVELOPES=<SAML_SIGNED_ENVELOPES>
....
. Restart the application.

==== Enabling SAML when using Docker images

To enable SAML when using Docker images, proceed as follows:

[arabic]
. If `+trento-web+` container is already running stop and delete the
container before continuing. For that run:
+
[source,bash]
----
docker stop trento-web
docker rm trento-web
----
. Use the following environment variables to the Docker container via
the `+-e+` option:
+
[source,bash]
----
docker run -d \
-p 4000:4000 \
--name trento-web \
--network trento-net \
--add-host "host.docker.internal:host-gateway" \

...[other settings]...

-e ENABLE_SAML=true
-e SAML_IDP_ID=<SAML_IDP_ID> \
-e SAML_SP_ID=<SAML_SP_ID> \
# Only SAML_METADATA_URL or SAML_METADATA_CONTENT must by provided
-e SAML_METADATA_URL=<SAML_METADATA_URL> \
-e SAML_METADATA_CONTENT=<SAML_METADATA_CONTENT> \

# Optional:
-e SAML_IDP_NAMEID_FORMAT=<SAML_IDP_NAMEID_FORMAT> \
-e SAML_SP_DIR=<SAML_SP_DIR> \
-e SAML_SP_ENTITY_ID=<SAML_SP_ENTITY_ID> \
-e SAML_SP_CONTACT_NAME=<SAML_SP_CONTACT_NAME> \
-e SAML_SP_CONTACT_EMAIL=<SAML_SP_CONTACT_EMAIL> \
-e SAML_SP_ORG_NAME=<SAML_SP_ORG_NAME> \
-e SAML_SP_ORG_DISPLAYNAME=<SAML_SP_ORG_DISPLAYNAME> \
-e SAML_SP_ORG_URL=<SAML_SP_ORG_URL> \
-e SAML_USERNAME_ATTR_NAME=<SAML_USERNAME_ATTR_NAME> \
-e SAML_EMAIL_ATTR_NAME=<SAML_EMAIL_ATTR_NAME> \
-e SAML_FIRSTNAME_ATTR_NAME=<SAML_FIRSTNAME_ATTR_NAME> \
-e SAML_LASTNAME_ATTR_NAME=<SAML_LASTNAME_ATTR_NAME> \
-e SAML_SIGN_REQUESTS=<SAML_SIGN_REQUESTS> \
-e SAML_SIGN_METADATA=<SAML_SIGN_METADATA> \
-e SAML_SIGNED_ASSERTION=<SAML_SIGNED_ASSERTION> \
-e SAML_SIGNED_ENVELOPES=<SAML_SIGNED_ENVELOPES> \

...[other settings]...
----

==== Available variables for SAML

SAML_IDP_ID::
  SAML IDP id
SAML_SP_ID::
  SAML SP id
SAML_METADATA_URL::
  URL to retrieve the SAML metadata xml file. One of
  `+SAML_METADATA_URL+` or `+SAML_METADATA_CONTENT+` is required
SAML_METADATA_CONTENT::
  One line string containing the SAML metadata xml file content
  (`+SAML_METADATA_URL+` has precedence over this)
SAML_IDP_NAMEID_FORMAT::
  SAML IDP name id format, used to interpret the attribute name. Whole
  urn string must be used (default value:
  `+urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified+`)
SAML_SP_DIR::
  SAML SP directory, where SP specific required files (such as
  certificates and metadata file) are placed (default value:
  `+/etc/trento/saml+`)
SAML_SP_ENTITY_ID::
  SAML SP entity id. If it is not given, value from the metadata.xml
  file is used
SAML_SP_CONTACT_NAME::
  SAML SP contact name (default value: `+Trento SP Admin+`)
SAML_SP_CONTACT_EMAIL::
  SAML SP contact email (default value: `+admin@trento.suse.com+`)
SAML_SP_ORG_NAME::
  SAML SP organization name (default value: `+Trento SP+`)
SAML_SP_ORG_DISPLAYNAME::
  SAML SP organization display name (default value:
  `+SAML SP build with Trento+`)
SAML_SP_ORG_URL::
  SAML SP organization url (default value:
  `+https://www.trento-project.io/+`)
SAML_USERNAME_ATTR_NAME::
  SAML user profile "username" attribute field name. This attribute must
  exist in the IDP user (default value: `+username+`)
SAML_EMAIL_ATTR_NAME::
  SAML user profile "email" attribute field name. This attribute must
  exist in the IDP user (default value: `+email+`)
SAML_FIRSTNAME_ATTR_NAME::
  SAML user profile "first name" attribute field name. This attribute
  must exist in the IDP user (default value: `+firstName+`)
SAML_LASTNAME_ATTR_NAME::
  SAML user profile "last name" attribute field name. This attribute
  must exist in the IDP user (default value: `+lastName+`)
SAML_SIGN_REQUESTS::
  Sign SAML requests in the SP side (default value: `+true+`)
SAML_SIGN_METADATA::
  Sign SAML metadata documents in the SP side (default value: `+true+`)
SAML_SIGNED_ASSERTION::
  Require to receive SAML assertion signed from the IDP. Set to false if
  the IDP doesn't sign the assertion (default value: `+true+`)
SAML_SIGNED_ENVELOPES::
  Require to receive SAML envelopes signed from the IDP. Set to false if
  the IDP doesn't sign the envelopes (default value: `+true+`)


////
End of sso-integration.xml article inside of systemd-install.xml
Source: https://github.com/SUSE/doc-unversioned/blob/main/trento/xml/sso-integration.xml
////

== Install and configure NGINX

. Install NGINX package:
+
[source,bash]
----
zypper install nginx
----
. If firewalld is running, add firewalld rules for HTTP and HTTPS:
+
[source,bash]
----
firewall-cmd --zone=public --add-service=https --permanent
firewall-cmd --zone=public --add-service=http --permanent
firewall-cmd --reload
----
. Start and enable NGINX:
+
[source,bash]
----
systemctl enable --now nginx
----
. Create a configuration file for Trento:
+
[source,bash]
----
vim /etc/nginx/conf.d/trento.conf
----
. Add the following configuration to `+/etc/nginx/conf.d/trento.conf+`:
+
....
server {
    # Redirect HTTP to HTTPS
    listen 80;
    server_name trento.example.com;
    return 301 https://$host$request_uri;
}

server {
    # SSL configuration
    listen 443 ssl;
    server_name trento.example.com;

    ssl_certificate /etc/nginx/ssl/certs/trento.crt;
    ssl_certificate_key /etc/ssl/private/trento.key;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers 'ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384';
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;

    # Wanda rule
    location ~ ^/(api/checks|api/v1/checks|api/v2/checks|api/v3/checks)/  {
        allow all;

        # Proxy Headers
        proxy_http_version 1.1;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_set_header X-Cluster-Client-Ip $remote_addr;

        # Important Websocket Bits!
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_pass http://localhost:4001;
    }

    # Web rule
    location / {
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;

        # The Important Websocket Bits!
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_pass http://localhost:4000;
    }
}
....
. Check the NGINX configuration:
+
[source,bash]
----
nginx -t
----
+
If the configuration is correct, the output should be as follows:
+
[source,bash]
----
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
----
+
If there are issues with the configuration, the output indicates what
needs to be adjusted.

=== Prepare SSL certificate for NGINX

Create or provide a certificate for https://nginx.org/en/[NGINX] to
enable SSL for Trento.

==== Create a self-signed certificate

. Generate a self-signed certificate:
+
[NOTE]
====
Adjust `+subjectAltName = DNS:trento.example.com+` by replacing
`+trento.example.com+` with your domain and change the value `+5+` to
the number of days for which you need the certificate to be valid. For
example, `+-days 365+` for one year.
====
+
[source,bash]
----
openssl req -newkey rsa:2048 --nodes -keyout trento.key -x509 -days 5 -out trento.crt -addext "subjectAltName = DNS:trento.example.com"
----
. Copy the generated `+trento.key+` to a location accessible by NGINX:
+
[source,bash]
----
cp trento.key /etc/ssl/private/trento.key
----
. Create a directory for the generated `+trento.crt+` file. The
directory must be accessible by NGINX:
+
[source,bash]
----
mkdir -p /etc/nginx/ssl/certs/
----
. Copy the generated `+trento.crt+` file to the created directory:
+
[source,bash]
----
cp trento.crt /etc/nginx/ssl/certs/trento.crt
----
. Reload NGINX to apply changes:
+
[source,bash]
----
systemctl reload nginx
----

==== Create a signed certificate with Let's Encrypt using PackageHub repository

[NOTE]
====
Change repository if you use a Service Pack other than SP5. For example:
`+SUSEConnect --product PackageHub/15.3/x86_64+` for SLE15 SP3,
`+SUSEConnect --product PackageHub/15.4/x86_64+` for SLE15 SP4. Use
packages in PackageHub at your own risk.
====

. Add PackageHub, if it is not already added:
+
[source,bash]
----
SUSEConnect --product PackageHub/15.5/x86_64
zypper refresh
----
. Install Certbot and its NGINX plugin:
+
[source,bash]
----
zypper install certbot python3-certbot-nginx
----
. Obtain a certificate and configure NGINX with Certbot:
+
[NOTE]
====
Replace `+example.com+` with your domain. For more information, refer to
https://certbot.eff.org/instructions?ws=nginx&os=leap[Certbot
instructions for NGINX]
====
+
[source,bash]
----
certbot --nginx -d example.com -d www.example.com
----
+
[NOTE]
====
Certbot certificates are valid for 90 days. Refer to the above link for
details on how to renew certificates.
====

== Accessing the trento-web UI

Pin the browser to `+https://trento.example.com+`. You should be able to
login using the credentials specified in the `+ADMIN_USER+` and
`+ADMIN_PASSWORD+` environment variables.
