# See https://golangci-lint.run/usage/linters/
linters:
  enable:
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    - containedctx
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errchkjson
    - errorlint
    - exhaustive
    - exportloopref
    - forbidigo
    - forcetypeassert
    - gochecknoglobals
    - goconst
    - gocritic
    - gofmt
    - gomoddirectives
    - gomodguard
    - gosec
    - ifshort
    - importas
    - lll
    - misspell
    - nilerr
    - nilnil
    - nonamedreturns
    - nosnakecase
    - prealloc
    - predeclared
    - revive
    - unconvert
    - unparam
    - wastedassign
