name: Publish Trento documentation on GitHub Pages
on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: '0 13 * * 4' # Every Thursday at 1:00 PM UTC
concurrency:
  group: github-pages
  cancel-in-progress: false
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-24.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      with:
        fetch-depth: 0
    - name: Configure Pages
      uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b # v5
    - name: Install Node.js
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
      with:
        node-version: '18'
    - name: Install Antora with the Antora Lunr Extension
      working-directory: trento-docs-site
      run: npm i antora @antora/lunr-extension
    - name: Generate Site
      working-directory: trento-docs-site
      run: npx antora antora-playbook.yml
    - name: Upload Artifacts
      uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v4.0.0
      with:
        path: trento-docs-site/build/trento-docs-site-public
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4
