# SPDX-FileCopyrightText: SUSE LLC
# SPDX-License-Identifier: Apache-2.0

name: Publish Trento documentation on GitHub Pages
on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: '0 13 * * 4' # Every Thursday at 1:00 PM UTC
concurrency:
  group: github-pages
  cancel-in-progress: false
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    uses: ./.github/workflows/reusable-build-docs-site.yaml
    with:
      upload-pages-artifact: true
  deploy:
    needs: build
    runs-on: ubuntu-24.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4
