# SPDX-FileCopyrightText: SUSE LLC
# SPDX-License-Identifier: Apache-2.0

name: Validate user facing documentation

on:
  push:
    branches: [main]
    paths:
      - 'trento/DC-*'
      - 'trento/xml/**'
      - 'trento/adoc/**'
      - 'trento/images/src/**'
  workflow_dispatch:

jobs:
  validate-suse-docs:
    uses: ./.github/workflows/reusable-validate-suse-docs.yaml
